### ISSUE TITLE
exiftool

### ISSUE THREAD

**Issue by tmtfx** [haikuports/haikuports#10788]
The first row of exiftool (a perl script) is this:
#!/packages/perl-5.40.0-1/.self/bin/perl -w

instead of /bin/perl or whatever more convenient, so launching exiftool from commandline the result is:

~> exiftool 
runtime_loader: Cannot open file /packages/perl-5.40.0-1/.self/bin/perl (needed by <NULL>): No such file or directory

**Comment by Begasus** [comment]
A revbump should fix this:
```
~/Desktop> exiftool 
Syntax:  exiftool [OPTIONS] FILE

Consult the exiftool documentation for a full list of options.
```

**Comment by jmairboeck** [comment]
The general problem is that perl scripts get the full path as interpreter path. Maybe we should fix this in a more general way.

**Comment by jmairboeck** [comment]
We use a bit of an usual shebang here:

https://github.com/haikuports/haikuports/blob/24f5b0d9ef5290b5e8cb8e403397417994274b82/dev-lang/perl/perl-5.40.0.recipe#L115

but MakeMaker looks for a string containing `/perl` (note the slash):

https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/5b79f2e55bfa308a282f5abbd1733cfd1d7862db/lib/ExtUtils/MM_Unix.pm#L1300

Can we change our shebang somehow so that it contains that but stays perl installation path agnostic (supporting user installations) but not be dependent on the exact revision of the perl package? Or can we assume that perl is always system-installed and just use `/bin/perl`?

**Comment by jmairboeck** [comment]
I noticed that this version (and the new one) is actually considered a "development version" (see https://exiftool.org/history.html). I hadn't noticed this during the previous upgrade. But now it comes handy because the newer versions (since 12.90) changed the shebang to one which we support better.
