### ISSUE TITLE
Clarify status of non-main branches

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1152]
So, at present, there are two new branches in this repository:
 * `2017Q1`, apparently created by @korli 
 * `release`, created by @pulkomandy.

The latter of these was discussed on the mailing list and I understand its purpose (frozen set of pre-tested packages for the b1 release -- this should probably be documented on the wiki somewhere, though). The other one, I don't know why it exists -- it seems to be vaguely a competitor to the `release` branch?

@korli, some explanation/clarification here would be nice (or a link to a discussion where this was covered that I somehow missed would be nice, too...)

**Comment by korli** [comment]
Sorry I thought it was obvious, I use 2017Q1 as a stable branch to synchronize the x86_64 package build on Haiku trunk.

**Comment by pulkomandy** [comment]
I also don't understand why we ended up with these two branches. But certainly we don't really agree on the best way to manage the release branch.

For the "release" branch I focused on x86_gcc2 for now. I try to keep that branch up to date with what is in the haikuports binary repo. I created it using a script that parses the repo definitions from Haiku sources, and tries to locate matching recipes in haikuports history. Then, I run the build bots on it, and update packages until I can get a set of packages that can be built all together without any problems. My goal was to work on a restricted set of packages, because getting everything in haikuports to work simply was too much work. On the other hand, if I follow correctly, 2017Q1 was created as a fork of the main branch and has all the recipes. However, most don't declare support for x8_64, so it isn't a problem there.

I think the branch could be shared more with the 2017Q1 one, but maybe it is a bit early to do that, as work to fix one platform could break the other. Maybe we can attempt that merge a little later when things in either branch have stabilized a little and when the buildbots are up and running.

**Comment by waddlesplash** [comment]
> because getting everything in haikuports to work simply was too much work. 

Can't we run the buildbots in a "build all that works, warn if it broke" mode?

> I think the branch could be shared more with the 2017Q1 one, but maybe it is a bit early to do that, as work to fix one platform could break the other. Maybe we can attempt that merge a little later when things in either branch have stabilized a little and when the buildbots are up and running.

OK, I suppose.

**Comment by pulkomandy** [comment]
> Can't we run the buildbots in a "build all that works, warn if it broke" mode?

There are two problems with that.

First, it makes it hard to track the status. I would like to know if a package is going to disappear from the repo because the recipe matching is currently broken (there are several packages in that case still). Having lots of failed packages in the release branch makes it harder to see when there are more of these appearing, and I think over time we will just end up with more and more broken recipes in the branch. Starting from an "everything builds" state means it is easier to stay there, and that regressions are easily spotted.

Second, with the current (low) number of build slaves, it takes more than 24 hours to go through a full build of even the release branch. It even rarely get through because the slaves will get stuck, either on a KDL or waiting for someone to click on "save report" on the crash report dialog. I think it is even worse for the complete repo, kallisti5 may tell us as he tried that. Focusing on a smaller set of packages, at least for now, allows us to test the architecture with more reasonable turnaround times. Once we have it running stable, we can consider a larger package set.

**Comment by korli** [comment]
Can we close this issue?

**Comment by pulkomandy** [comment]
We still don't have an answer on how we're going to manage beta/trunk of haiku. The "release" branch is unneeded because master is automatically in sync with the repos now. But I still don't know if there should be a separate branch for beta users (more stable system for the users, but more work for the maintainers with two branches to keep running). Maybe we should rather handle this at the repo level?

**Comment by alaviss** [comment]
Well, maybe an another issue should be made for that?

**Comment by waddlesplash** [comment]
At this point we have decided on having HaikuPorts always build against the beta branch until shortly before the next beta. Probably we will have to revisit that when it comes time for R1, but at least for now, things seem to be working out.
