### ISSUE TITLE
lftp: ftp -- not supported protocol

### ISSUE THREAD

**Issue by walkerlala** [haikuports/haikuports#1248]
In Haiku, after installing lftp (version 4.416 or version 4.7.7) and using it to get some file from some ftp sites, you will get the "ftp -- not supported protocol" when starting the program. This is ridiculous. But I notice that if you build it manually (without haikuporter) and run, everything is fine. Does anyone have any idea about what is going on? I think there might be some libs missing, but I can't find the solution.

**Comment by diversys** [comment]
Maybe you can run it with strace? e.g. `strace lftp` and see if there's some hint

**Comment by pulkomandy** [comment]
Maybe there is a problem with packaging it and either one of:
- It fails to find some required files or libraries, in which case, you could see it in strace (look for "open" on .so files for example?). Either the libs are not at the expected place, or they are completely missing from the package
- It tries to write some file in a non-writable directory (look in strace for "open" in write mode). Most of /system/ is not writable for software in packages.

**Comment by walkerlala** [comment]
There is a lib `liblftp-network.so` missing. But I cannot find the right method to fix it yet.

I try to add `lib:liblftp_network` to **PROVIDES** and `devel:liblftp_network` to **PROVIDES_devel**, just like it was did for `liblftp_jobs` and `liblftp_tasks`. But, after I change the line in the **INSTALL** section from 

    prepareInstalledDevelLibs liblftp-jobs liblftp-tasks

to 

    prepareInstalledDevelLibs liblftp-jobs liblftp-tasks liblftp-network

Haikuporter fail to build the package, complaining
>mv: cannot stat '/packages/lftp-4.7.7-1/.self/lib/liblftp-network.*': No such file or directory

So clearly there is something wrong with this `liblftp-network.so` lib.

**Comment by pulkomandy** [comment]
Ok, strace shows that proto-ftp.so is correctly found, but it in turn depends on liblftp-network.so. It seems that the runtime_loader does not think to look in the same directory as the .so to find that dependency, and it fails.
The libraries are in lib/lftp/4.4.16/, which is fine, since we may not want them to be easily visible to other applications.

The simplest solution is to remove --with-modules from the recipe, so the protocols are built into the executable and there is no need to load them as libraries.
