### ISSUE TITLE
wpa_supplicant should be updated

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#1290]
Current recipe is for 2.0 but the 2.6 version already available: http://w1.fi/releases/wpa_supplicant-2.6.tar.gz

Patchset doesn't apply cleanly anymore, needs adjusts.

**Comment by kallisti5** [comment]
https://www.freelists.org/post/haiku-development/wpa-supplicant,8

**Comment by kenmays** [comment]
I created the wpa_supplicant 2.6-patchset and recipe. The 2.6-patchset updates cleanly based from the 2.0-patchset with Haiku changes and adds all security updates. Reviewing the Haiku changes a bit more so W-I-P for now.

**Comment by pulkomandy** [comment]
As mentionned in #2160, but repeating here for ease of navigation:

I have a version of wpa_supplicant 2.4 here: https://github.com/pulkomandy/wpa_supplicant-haiku
It includes Haiku patches updated to 2.4 codebase, and briefly tested on my machine. We should update to that for a start. In later versions of wpa_supplicant, the interface between the cross platform and platform-specific code has changed (IIRC it now uses a single socket, instead of one socket per interface). So the Haiku code needs to be adjusted for this.

**Comment by waddlesplash** [comment]
+1. I already assigned the ticket to myself and started working on it.

**Comment by kenmays** [comment]
@waddlesplash - Built 2.7-dev package(s). Please review for resolution: https://dev.haiku-os.org/ticket/8850
Thank you.

**Comment by waddlesplash** [comment]
As that ticket says, it needs changes to wpa_supplicant and Haiku itself. So of course it isn't fixed.
