### ISSUE TITLE
cmake: Find* modules needs to be patched

### ISSUE THREAD

**Issue by miqlas** [haikuports/haikuports#1297]
Currently the FindLua file provided by cmake cannot locate the required libs and headers as the predefined searchpaths doesn't include the standard Haiku paths, see here:
https://github.com/Kitware/CMake/blob/master/Modules/FindLua.cmake#L157

Maybe other modules needs to be patched too.

**Comment by pulkomandy** [comment]
CMake is usually ok with upstreaming the changes (if done right) and they have a friendly IRC channel. We have already patched several modules (freetype, fontconfig, SDL, ...).

**Comment by miqlas** [comment]
I've seen, but there is still some notorious Find* modules which defines search locations and it isn't the right way to patch it every time. It would be nice to implement the required changes only once and have party all night long.
I will look into this.

**Comment by phoudoin** [comment]
IIRC, CMake's find_library will search in CMake's Plateform variables, in particular CMAKE_SYSTEM_LIBRARY_PATH, CMAKE_SYSTEM_FRAMEWORK_PATH and CMAKE_SYSTEM_PREFIX_PATH, except when it'e explicitly disabled. 

So far, the Haiku.cmake platform file seems to set the right values to find an "liblua.so*" either in system libs or develop libs.

The actual issue comes from FindLua.cmake alas. It assume that lua.h will always be installed under some include/lua<version> folder. The include/ root folder is wrongly enforced here, and that's plain wrong.

In particular because find_path() will search by default in CMAKE_SYSTEM_INCLUDE_PATH which will already have "include" folder there for platforms where it make sense, and /boot/develop/headers for Haiku platform.

A quick test show that removing the include/ parts let find_package(Lua) works as expected with lua-devel packages. Didn't have time to check if it break something on others platforms, but I'll bet it wont too.

**Comment by Begasus** [comment]
in case of lua, there was a missing *.pc file, iirc it was added and is picked up correctly now  :)

**Comment by Begasus** [comment]
Is still valid? @miqlas @phoudoin

**Comment by miqlas** [comment]
I suppose it is solved already with the freshly introduced SDL2 .pc file (thanks @korli !) and with your work, @Begasus!

**Comment by Begasus** [comment]
Maybe this can be closed also then :)

**Comment by phoudoin** [comment]
if it's fixed since lua have correct pconfig, let's close this issue, indeed.

**Comment by miqlas** [comment]
Aye-Aye!
