### ISSUE TITLE
git: config parameter adds .gitconfig in ~/

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#1506]
The patch to use ~/config/settings/git/config does the reading of the settings perfectly.
Doing e.g. `git config --global user.name "Humdinger"`, however, still writes to ~/.gitconfig.

**Comment by phoudoin** [comment]
It may be related to the initial creation of a default ~/.gitconfig at first commit without user.* defined, leading to ~/.gitconfig being the first write target everytime then. Try to move/merge it to ~/config/settings/git/config, I'll bet that writing will fall there, then.

Will dive deeper to find the root cause and fix when get some free time.

**Comment by sfanxiang** [comment]
https://github.com/git/git/blob/1eaabe34fc/builtin/config.c#L528 suggests that `~/config/settings/git/config` is preferred as long as it exists.

Maybe add it to USER_SETTINGS_FILES?

**Comment by sfanxiang** [comment]
https://github.com/git/git/blob/1eaabe34fc/builtin/config.c#L528 suggests that `~/config/settings/git/config` is preferred as long as it exists.

Maybe add it to USER_SETTINGS_FILES?
