### ISSUE TITLE
Write a recipe for FocusWriter

### ISSUE THREAD

**Issue by return** [haikuports/haikuports#1596]
A Qt5-based distraction-free word processor. I haven't tried its ODT document support though, but it
should compile on Haiku without any changes.

https://gottcode.org/focuswriter
https://github.com/gottcode/focuswriter

**Comment by korli** [comment]
Please post a pull request.

**Comment by dasouth1** [comment]
Hi Korli! I did create a pull request at the following:

https://github.com/dasouth1/haikuports/pulls

**Comment by korli** [comment]
Ok but that's a pull request at your repository. Why not on this repository?

**Comment by dasouth1** [comment]
I've been having issues with my network, and I was trying everything I could just to create a pull request.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jérôme DuvalSent: Saturday, September 23, 2017 1:15 AMTo: haikuports/haikuportsReply To: haikuports/haikuportsCc: dasouth1; CommentSubject: Re: [haikuports/haikuports] Write a recipe for FocusWriter (#1596)Ok but that's a pull request at your repository. Why not on this repository?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haikuports/haikuports","title":"haikuports/haikuports","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/haikuports/haikuports"}},"updates":{"snippets":[{"icon":"PERSON","message":"@korli in #1596: Ok but that's a pull request at your repository. Why not on this repository?"}],"action":{"name":"View Issue","url":"https://github.com/haikuports/haikuports/issues/1596#issuecomment-331613849"}}}

.

**Comment by dasouth1** [comment]
I've been having network issues yesterday and today, and I was trying anything I could think of to do a pull request.

**Comment by korli** [comment]
The commit on your branch is empty anyway. You should check first the files at your branch.

**Comment by dasouth1** [comment]
Can you confirm that a pull request was finally created? I also deleted my branch to try to simplify things.

**Comment by miqlas** [comment]
@dasouth1 : I can't see it.

**Comment by dasouth1** [comment]
[Focuswriter.zip](https://github.com/haikuports/haikuports/files/1326744/Focuswriter.zip)

**Comment by miqlas** [comment]
@dasouth1 : Attaching as zip is not ok.

**Comment by miqlas** [comment]
@dasouth1 
1) fork the haikuports repo
2) clone the fork to your computer
3) create a feature-branch
4) do your changes
5) commit it locally
6) push it to your fork
7) create a PR

Report back if something unclear.

**Comment by dasouth1** [comment]
Having this issue:

error: failed to push some refs to 'https://github.com/dasouth1/haikuports'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/haikuports> git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
~/haikuports>

**Comment by miqlas** [comment]
Clone it again, and do your changes again in a feature branch.
Be careful to not change anything else, just what you really want to.

If it still not works i'll guide you step-by-step.

**Comment by dasouth1** [comment]
Stil no luck! I can see when I do a commit, and when I push it to my fork. But I've tried a couple different times to create a pull request with no success, I had one earlier today that failed (which I was glad because I combined both changes to Trojita with the receipe for Focuswriter).

**Comment by pulkomandy** [comment]
"clone it again" is the brute force way of doing it (aka https://xkcd.com/1597/)

Judging from your current state, you need to:

    git merge --abort
    git pull --rebase

This should put things back in working order, I think.

**Comment by korli** [comment]
Added in 1613ab326e59602fee9f9ce2f62b1d16d83cd995
