### ISSUE TITLE
Lots of missing packages that Haiku depends on for build in new repos

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1709]
On x86_gcc2, the following packages are missing (i.e. no version of them whatsoever is in https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_gcc2/current/packages/):
- [ ] gcc_x86
- [ ] gcc_x86_syslibs
- [ ] gcc_x86_syslibs_devel
- [ ] llvm_x86
- [ ] llvm_x86_clang
- [ ] llvm_x86_clang_analysis
- [ ] llvm_x86_libs
- [ ] mesa_x86
- [ ] mesa_x86_devel
- [ ] mesa_x86_swpipe

Help wanted (everyone).

**Comment by waddlesplash** [comment]
Hmm, it appears most of these were supposed to be built as part of Build 272 but the builder disconnected: https://kitchen.haiku-os.org/master/x86_gcc2/?buildrunDir=272&viewMode=expanded

@mmlr: If the builder fails to connect, do all the packages just get marked "failed to build" and are never tried again???

**Comment by mmlr** [comment]
> Hmm, it appears most of these were supposed to be built as part of Build 272 but the builder disconnected: https://kitchen.haiku-os.org/master/x86_gcc2/?buildrunDir=272&viewMode=expanded

Not sure where you see "most of these" in that buildrun.

> If the builder fails to connect, do all the packages just get marked "failed to build" and are never tried again???

No, the ports don't get marked as failed to build due to builder errors, only on actual build errors. As can be seen in buildruns 273 through 277 the same set of 65 packages were indeed retried. That they were skipped on buildrun 278 was then owed to the problem of corrupted/packages causing dependency resolution to fail. This was fixed in 5c66dddf84cab05f28003645668b25d89b705836 and 538d48adb92e2661da33a6ca1286d6ee94bf813b for each respective case. I have reset the processed_rev marker so that the lost packages will be retried again.

As explained on the mailing list the explanation of the missing packages is as simple as "the corresponding recipes/files have not been touched since the buildmaster was set up". I'll look into scheduling a buildrun that catches up the missing packages.

**Comment by waddlesplash** [comment]
@mmlr: OK, so most of these packages were indeed built, and so I've updated the list to include only the packages we don't have. It looks like binutils failures might be causing all the rest at this point... Thanks for your work so far.

**Comment by unspacyar** [comment]
Hello waddlesplash. About the list: the libQt4 packages also need to be updated, isn't?  I don't see it in the gcc2 repo.

**Comment by waddlesplash** [comment]
@unspacyar: This is only about packages that Haiku needs for a build. Not all packages in the repo.
