### ISSUE TITLE
Kdiff3: the config file is placed in the Home folder instead of ~/config/settings

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1820]
I updated Haiku yesterday from hrev51400 to hrev51639: I had an older revision of Kdiff3 and the config file .kdiff3rc was placed in /boot/home/config/settings/Qt. Now, also with the new revision of Kdiff3, .kdiff3rc is just placed in the /home folder.

**Comment by bach5000** [comment]
I found the parts of the code where the program references the home directory :)
* https://github.com/Stibbons/kdiff3/blob/master/kdiff3/src-QT4/kreplacements/kreplacements.cpp#L426
and...
* https://github.com/Stibbons/kdiff3/blob/master/kdiff3/src-QT4/fileaccess.cpp#L1392

I fixed these using `find_directory` and `ifdef __HAIKU__`: except...
* I have some current issues with haikuporter, so I can't really test these changes :(
* I can't seem to make a patch file, but... I have this:
https://github.com/Stibbons/kdiff3/compare/master...bach5000:homedir

Any suggestions to the code would be welcome (in fact, please do make suggestions, since I wasn't able to test it)
