### ISSUE TITLE
QT doesn't copy/paste?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1842]
copy/paste works inside QupZilla, copy/paste from Terminal (or any other) doesn't seem to work inside QupZilla ...

**Comment by Lan72** [comment]
I confirm the problem. And it does not happen from the very beginning. 
The first minutes copy/paste works fine, but then troubles begin. The clipboard instead of the data copied now takes the previous data. This is observed not only in QupZilla, but also in Otter Browser, who work under Qt 5.9.3.
Under Qt 5.9.2 this wasn’t, and it began to be observed with the installation Qt 5.9.3.

**Comment by threedeyes** [comment]
what revision of the qthaikuplugins package is installed?

**Comment by humdingerb** [comment]
Here it's qthaikuplugins_x86-1.0~git-11-x86_gcc2.hpkg

**Comment by Giova84** [comment]
This also occunrs with Notepadqq, so is definitely an issue with QT5 port.

**Comment by diversys** [comment]
There were a recent changes to clipboard code in https://github.com/threedeyes/qthaikuplugins/commit/da42e0459630d0b59c201c3c76b380e60ba1a60c. Maybe someone could try to revert it and see if that fixes it?

**Comment by Lan72** [comment]
**diversys**

I listened to your advice and rebuilt the qthaikuplugins module, and returning back to their original place old _qhaikuclipboard.cpp_ and _qhaikuclipboard.h_.

While everything seems to be fine with the clipboard. I wonder for how long? Before that, the clipboard was already jammed.

**Comment by extrowerk** [comment]
can we close this?
