### ISSUE TITLE
UltraDV - no link to Applications menu

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2037]
After installing UltraDV package from HaikuPorts, I found that the link to the Applications menu is missing.

**Comment by fbrosson** [comment]
FWIW, I tried updating to https://github.com/Barrett17/UltraDV/commit/2a27d23d6924fdcd12d2d73fe50b9d3edb573b75 but it only worked on x86_gcc2. On x86_64 there is something wrong. So I just fixed the issue about the app not having an entry in the Applications menu.
If anyone wants to try with the latest commit:
```diff
-gitCommit="886aad8b0456372d049642de424cc58663b9a977"
+gitCommit="2a27d23d6924fdcd12d2d73fe50b9d3edb573b75"
 SOURCE_URI="https://github.com/Barrett17/UltraDV/archive/$gitCommit.tar.gz"
-CHECKSUM_SHA256="eb2f23a964613eaf3ae364e70a1d4338363b06d99f3a788f044d70ece028c1cb"
+CHECKSUM_SHA256="a8db17369ca1aebeb2897c838c0c939295a6a0c59525a5c54904cd61b54c8160"
```
I'm closing this issue since it is now fixed :)
