### ISSUE TITLE
retroarch is still attempting to pull fbalpha_libretro

### ISSUE THREAD

**Issue by kwyxz** [haikuports/haikuports#2296]
Hello,
Due to an erroneous use of SUPPLEMENTS when packaging fbalpha_libretro, installing RetroArch is still attempting to pull an older (0.2.97.42.git20180226) version of the fbalpha_libretro package despite a newer one (0.2.97.42_20180306) being already merged. Is there something that can be done to remedy this?
Thanks!

**Comment by kwyxz** [comment]
I just realized that 0.2.97.42_20180306 doesn't build. That's probably not helping. Looking into this.

**Comment by kwyxz** [comment]
This is very weird: I built the very same revision properly a few days ago https://github.com/haikuports/haikuports/pull/2283#discussion_r172592385 and now it's not building. WTF.

**Comment by kwyxz** [comment]
And now I just retried the build, without doing anything else, and it builds. This is super weird. But at least we're back to the original issue now.

**Comment by kwyxz** [comment]
Yeah it's confusing. I'm working on a new libretro core PR (yay) and this new one broke a few minutes after building fine as well. Now it builds fine again.
Can anything be done regarding the SUPPLEMENTS thing?

**Comment by fbrosson** [comment]
OK, I know what's happening. `pkgman install retroarch` is pulling the "wrong" versions:
```
    install package retroarch_assets-0~git20180129-1 from repository HaikuPorts
    install package fbalpha_libretro-0.2.97.42.git20180226-1 from repository HaikuPorts
    install package bsnes_libretro-0.94.git20171227-1 from repository HaikuPorts
    install package retroarch-1.7.1-1 from repository HaikuPorts
```
pkgman thinks the wrong versions are newer than the correct versions.
That's because "g" > "_".

Package | wrong version | correct version
-- | -- | --
fbalpha_libretro | 0.2.97.42.git20180226 | 0.2.97.42_20180306
bsnes_libretro | 0.94.git20171227 | 0.94_20171227

**Comment by fbrosson** [comment]
Hmm, I forgot the dot. Normaly pkgman shoud find that `0.94.git20171227` is **_older_** than `0.94_20171227` (because `.` < `_`).
But for some reason unknown to me it thinks that `0.94.git20171227` is **_newer_** than `0.94_20171227`.

There is a small chance that bumping the `REVISION` for bsnes_libretro (or fbalpha_libretro) could fix this.
If it works than I'll bump the other one.
Shall I try it?

**Comment by kwyxz** [comment]
Sure!

**Comment by fbrosson** [comment]
It looks like it worked for bsnes_libretro:
```
The following changes will be made:
  in system:
    install package retroarch_assets-0~git20180129-1 from repository HaikuPorts
    install package fbalpha_libretro-0.2.97.42.git20180226-1 from repository HaikuPorts
    install package retroarch-1.7.1-1 from repository HaikuPorts
Continue? [yes/no] (yes) : 
```
So now I'll bump `REVISION` for fbalpha_libretro and that should do the trick :)

**Comment by fbrosson** [comment]
It looks like it also worked for fbalpha_libretro. `pkgman install retroarch` outputs:
```
The following changes will be made:
  in system:
    install package retroarch_assets-0~git20180129-1 from repository HaikuPorts
    install package retroarch-1.7.1-1 from repository HaikuPorts
Continue? [yes/no] (yes) : 
```
I guess the issue is solved ;)

**Comment by kwyxz** [comment]
Awesome, thanks!
