### ISSUE TITLE
Finish work on WIP recipes

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#260]
The recipes that were in PRs on BitBucket are now here: https://github.com/soakbot/haikuports/branches/all

They need to be cleaned up, completed, and merged at some point.

**Comment by waddlesplash** [comment]
The only PR I wasn't able to get was "516: minidlna rework". The person who created that PR deleted their repo, and so I can't back it up. BitBucket doesn't have a way to extract the patch from the PR, apparently (GitHub does)...

**Comment by pulkomandy** [comment]
https://github.com/soakbot/haikuports/tree/pr_backups/488-do-not-merge-add-a-new-app-driveencryption : recipe in tree, needs ColumnListView fixes.
https://github.com/soakbot/haikuports/tree/pr_backups/486-added-recipe-for-transplus : can be closed, recipe is in tree.
https://github.com/soakbot/haikuports/tree/pr_backups/491-dovecot-add-dovecot-2215-recipe-and-patch: can be closed, recipe is in tree.
https://github.com/soakbot/haikuports/tree/pr_backups/494-add-recipe-for-a-haiku-lib-sockhop: can be closed, recipe is in tree.

This leaves us with psirockin work.

**Comment by pulkomandy** [comment]
Here we go:
SDL_bomber: recipe in tree, builds ok
Cyberdogs_SDL: download links needs to be fixes (points to "master" git, so SHA mismatch)
abe: recipe in tree, download links need to be fixed to use standard sourceforge layout, policy errors.
eggchess: download link points ot git master, SHA mismatch.
mxml: problems with provides
bzflag: mising libcares?
gnurobbo: builds ok

Since we have recipes in tree for everything, I think we can close this bug and track each of them individually when needed.
