### ISSUE TITLE
colorcode_x86 and supertransball_x86 don't install by pkgman/HaikuDepot

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2784]
pkgman and HaikuDepot app won't install:

- colorcode_x86
- super_transball

**Comment by kenmays** [comment]
Tested on hrev52080 x86_gcc2:

1. super_transball - Manually installable. Stops working after intro screen. 
2. colorcode_x86 - Manually installable. Works (no major issues).

**Comment by alaviss** [comment]
Is there any messages appear when you do

    pkgman install super_transball

?

**Comment by kenmays** [comment]
For both packages, pkgman says 'can't find <packages>' yet the packages exist in the x86_gcc2 repo.

**Comment by extrowerk** [comment]
@kenmays : i'm almost sure it is the "recipe name isn't equal the provides" we used to have with other recipes before.

https://github.com/haikuports/haikuports/blob/75a3cf5384f650242f4b8a1094ab305d33ed99e7/games-arcade/super_transball/super_transball-2.1.5.recipe#L20
Super Transball provides "stransball2 " instead of "super_transball".

@kenmays : are you up to fix them? It should be easy, just fix the provides and bump the revision, test it on your computer and then send a PR.

**Comment by kenmays** [comment]
I'll review.

**Comment by kenmays** [comment]
@fbrosson @extrowerk - Ok fixed. Just need git permissions to push request to haikuports.

**Comment by extrowerk** [comment]
One doesnt just push commit into Haikuports, @kenmays.
Use feature branches and create a pull request.

**Comment by fbrosson** [comment]
@kenmays, here are a few hints about the steps needed to have your (local) commit pushed to the project's master branch:
1) First, clone the HaikuPorts repo using GitHub's web interface, in order to create your remote repo.
2) On your local repo, use:
```bash
git remote set-url origin https://github.com/kenmays/haikuports.git
git remote add upstream https://github.com/haikuports/haikuports.git
```
3) Create a [feature-branch](https://github.com/haikuports/haikuports/wiki/DevelopmentModel#what-are-feature-branches) with your current branch:
```bash
git checkout -b colorcode
```
4) Then you should be able to push that branch to your remote repo, and create a PR.

I'm not providing all the commands because I don't know how comfortable you are with Git, but please do not hesitate to ask if you need any guidance :)

My advice: 
1) always keep your local master branch clean, i.e. without any commits that are not already in the project's master.
2) Use `git checkout master && git pull upstream master` before a `git checkout -b my-changes` if you plan to create a pull request for some changes.

**Comment by kenmays** [comment]
@fbrosson - Closing this one as it is no longer an installation issue.  

super_transball - has a functional issue. Seems to crash on my hardware so will open a separate ticket on that. We can fix the recipe and issue once fixed in that ticket.
