### ISSUE TITLE
Code::Block - fatal error: ar.h: No such file or directory

### ISSUE THREAD

**Issue by AwlsomeAlex** [haikuports/haikuports#2790]
I'm currently in the process of porting Code::Block to Haiku OS (Because another Code Editor won't hurt) but I'm stuck at the make part with it crashing complaining:
`fileunix.c:125:11: fatal error: ar.h: No such file or directory`
`# include <ar.h>`

What dependency is needed to solve this? I've tried glib2_devel, unarr_dev, and glibmm_devel.
![capture](https://user-images.githubusercontent.com/11639639/42548664-3fc49930-8496-11e8-931a-9efca4577836.PNG)

**Comment by fbrosson** [comment]
Indeed, it would be cool to have Code::Block ported to Haiku!

On Debian, `/usr/include/ar.h` is provided by `libc6-dev`, so I guess Haiku should provide a `/boot/system/develop/headers/ar.h` in `haiku_devel`.
Until this happens you might wish to try using the `binutils`'s `include/aout/ar.h`, which seems to be equivalent or compatible with the one Debian ships in `libc-dev`. But you will probably need to grab a copy of the `ar.h` from `binutils` source tarball (because it is not available in Haiku's `binutils` package) and add it to your recipe inside a patchset.

**Comment by AwlsomeAlex** [comment]
Okay, should I either create a copy or move a copy to the include folder and reference it there?

**Comment by fbrosson** [comment]
`/boot/system/develop/headers/` (among many other directories) is read-only, so I think the easiest way to have the `ar.h` header found is to add it to an `include/` subdirectory of `Code::Blocks` and see if this works.
You might need to add a `CFLAGS` in case it does not work.

Another way is to create a tiny hpkg file, with a `develop/headers/ar.h` in it, and install that package.
But this is both an ugly hack and a bit tricky, because you would have to write a `.PackageInfo` file and use `package create ../my_ar_h_header-1.0-1-any.hpkg` to create that strange hpkg file. Moreover, this would not be a good idea at all.

Hmm, there a few other directories where you might try to copy the `ar.h` file:
* ` /boot/system/non-packaged/develop/headers/`
* ` /boot/home/config/non-packaged/develop/headers/`

They probably don't exist, but you can create them. I think this will be much better than my previous suggestions.
But if you write a recipe for `Code::Blocks` then I think you should not assume the `ar.h` file will be in any of these `non-packaged` directory trees.

(Good luck!)

**Comment by AwlsomeAlex** [comment]
When I get home I’ll make a patch of what I’ve got so far and change the include from <ar.h> to the include/header directory of Code::Blocks. After that I don’t see why it wouldn’t work as it’s main dependency WxWidget QT is already met. (Learned that the hard way trying to compile from source).

**Comment by waddlesplash** [comment]
> After that I don’t see why it wouldn’t work as it’s main dependency WxWidget QT is already met. (Learned that the hard way trying to compile from source).

The wxQt recipe as-is doesn't have working Cairo, and CodeBlocks may require that. However, as I noted in #1779, wxWidgets merged the branch we were using into master, and I believe it's in 3.1.1 final. So that may be worth looking into.

**Comment by AwlsomeAlex** [comment]
Okay so commenting out `# include <ar.h>` from fileunix.c:125 and moving ar.h from GlibC to the /include directory of Code::Block then including it as `#include "ar.h"` in the beginning of the file solved this problem! Fingers crossed nothing else happens and all is good. :)

**Comment by AwlsomeAlex** [comment]
Compiles! But another error arises….

**Comment by Begasus** [comment]
Adding Haiku in that file resolves the need for ar.h (using OS_HAIKU didn't seem to do the trick, maybe wxgtk needs a fix for that?)
```diff
# if defined( OS_QNX ) || \
     defined( OS_BEOS ) || \
+     defined(  __HAIKU__  ) || \
     defined( OS_MPEIX )
# define NO_AR
# define HAVE_AR
# endif
```
