### ISSUE TITLE
cppcheck: misconfigured CFGDIR

### ISSUE THREAD

**Issue by KapiX** [haikuports/haikuports#2914]
Tried running cppcheck on one .cpp file, got this:
```
cppcheck: Failed to load library configuration file 'std.cfg'. File not found
(information) Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with CFGDIR set to "/packages/cppcheck-1.84-1/.self/share/CppCheck" and will therefore search for std.cfg in that path.
```

**Comment by extrowerk** [comment]
That's strange, no cppcheck recipe moves/deletes files, and the path ```/packages/cppcheck-1.84-1/.self/share/CppCheck``` would trigger a haikuporter error (top level share folder not allowed).
@KapiX did you installed it from Depot?

**Comment by extrowerk** [comment]
Maybe one have to explicitly tell to cmake to install that file, OR the "share" folder landed somehow in the work folder as i've seen already on some cases, because the prefix was not defined. (<- this seems to be the case but we have to check it). Can you maybe build it locally and check the working folder?

**Comment by KapiX** [comment]
Yes, installed from HaikuDeport. Haikuporter would not trigger error, because the issue is that the folder *is not* there.

https://github.com/danmar/cppcheck/blob/master/cmake/compilerDefinitions.cmake#L8
