### ISSUE TITLE
QEMU needs build/CI host

### ISSUE THREAD

**Issue by cb88** [haikuports/haikuports#2916]
I just noticed Haiku was mentioned in the latest QEMU changelog. 
https://wiki.qemu.org/ChangeLog/3.0#Warning:_unsupported_host_systems

Not sure if the Haiku team wants to take this on but as I understand it there a new fast machine a lot of the packages etc are built on... so perhaps this would be a minor additional burden to add to it? 

I haven't really looked at the package building infrastructure but I imagine doing something like building for nightly and whatever the last stable is would be supported. 

As I understand an older version of QEMU has  a native interface but it isn't upstreamed... so perhaps it would be needed to either do that or just build with no graphical interface just as a smoke test for upstream to know they aren't breaking builds on Haiku.

**Comment by extrowerk** [comment]
Current QEMU have sdl based GUI too (this is what HaikuPorts currently using). A native GUI would be better, sure.
I don't think the HaikuPorts project needs to provide the CI builder, as their building infra. Somebody should setup it on an own server/vm isntance.

**Comment by pulkomandy** [comment]
The problem is not additional burden to the server itself, but to the people administrating it. It is yet another service to care for. And this is definitely not up to haikuports, which is only about packaging the software, and not maintaining everything.

So, one should send a call for help on Haiku forums/mailing list, and a team of maintainers for qemu be set up. Then they can request server space from haiku inc (or elsewhere) for a CI builder.

**Comment by pulkomandy** [comment]
Haiku forums, mailing lists (haiku@freelists.org) or IRC channel would be appropriate. Then once there is a team of maintainers, haiku-sysadmin@freelists.org to request resources on Haiku's server if needed.

**Comment by cb88** [comment]
https://bugs.launchpad.net/qemu/+bug/1715203
