### ISSUE TITLE
haikuporter doesn't always pick up after a revision bump

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#2934]
I've seen haikuporter building rev1 from a recipe while the recipe was bumped with a rev2, cleaning the build and start fresh (without touching the recipe) is ok then and builds the rev2 package ...

**Comment by Begasus** [comment]
Steps to reproduce, cp a recipe over from another VBox installation, the dependency doesn't get updated (probably because the other recipe is older then the installed one after a repopulatian of the tree?)

**Comment by Begasus** [comment]
Solution for now, clean the build before actually building the package ...

**Comment by Begasus** [comment]
Files need to be "touched" to update the dependencies it seems for haikuporter ...

**Comment by fbrosson** [comment]
@Begasus, in case your haikuports tree is in a network share then you might wish to try unmounting and remounting it. This ugly hack "works fine" with NFS shares, and I never need to `touch` a file.
(I export my haikuports tree with NFS from my Linux host to my Haiku VMs.)

BTW, I noticed some time ago that when one changes `ALLOW_UNTESTED` from `"no"` to `"yes"` then haikuporter does not update the `.DependencyInfo` files. (Sorry for not having reported this...) I guess the value of the `ALLOW_UNTESTED` setting should be associated to the state of the repository so that haikuporter can check that this setting did not change since the last invocation. (If it did then hp should rescan the tree, of course.)

**Comment by Begasus** [comment]
@fbrosson the haikuports tree are on the VBox installations, I connect to another one (in this case I booted my x86_64 install and connected to the gcc2h VBox installation and cp'd the files over) as the date isn't updated hp doesn't rescan the deppendency even if the revision is upped ... it could be a VBox thing but just wanted to report

**Comment by fbrosson** [comment]
I just realized the reason why your timestamps are confusing hp could be due to some incorrect VBox setting of your timezone.

**Comment by Begasus** [comment]
I'm guessing this can be closed :)
