### ISSUE TITLE
QupZilla is not storing/displaying new bookmarks favicon

### ISSUE THREAD

**Issue by Briseur** [haikuports/haikuports#2969]
Visit a site with favicon, bookmark it.
The favicon used to appear after a QupZilla new start but it isn't appearing anymore.
In addition, when adding a search engine it was possible to customize the favicon providing the site url, favicons are not appearing here either so default is always used.
Note that included bookmarks (QupZilla ones) and included search engines still have their favicons appearing.

**Comment by Briseur** [comment]
After investigation, the reason is that favicons and associated urls are stored in WebpageIcons.db which is always deleted after closing the app. It seems to be a workaround for an old qt5-qtwebkit vulnerability ( https://www.cvedetails.com/cve/CVE-2015-8079/ ). We are using a more recent version than that, aren't we? So I'm wondering if it is still necessary? In case it is, wouldn't it be enough to delete that file only if safe browsing is activated.

**Comment by waddlesplash** [comment]
QupZilla is deprecated and has not seen updates in a while; we should probably just remove it in favor of Otter.

**Comment by humdingerb** [comment]
Block-editing of the user guide currently only seems to work with QupZilla. Both Otter and Web+ fail. Maybe there's a working user agent setting for Otter, but it's not something anyone should be forced to twiddle with...

**Comment by waddlesplash** [comment]
The user agent is ignored by the Userguide Translator as far as I know, so changing user-agents will not affect anything.

"Child windows" are a lesser used feature of the web these days for one reason or another, which is probably why. If you have a Linux install, see if the bug replicates there; and if so, report a bug to Otter. I guess there is already a Web+ ticket?

**Comment by humdingerb** [comment]
I was pretty sure I already filed a ticket for that, but couldn't find it... Created [#15859](https://dev.haiku-os.org/ticket/15859) now.

I'll try Otter on Linux soon

**Comment by waddlesplash** [comment]
QupZilla removed in https://github.com/haikuports/haikuports/commit/6187dcea9436f01b87034f2af894608065b18caa.

**Comment by humdingerb** [comment]
Wasn't that a bit premature? We now have no way to edit the user guide under Haiku!
I'll have to back-up the current QupZilla package and make it available somewhere...

Otter under Linux doesn't work with the user guide site either.

**Comment by Begasus** [comment]
Created a backup for the package here also (locally) ...

**Comment by diversys** [comment]
I also think it was too fast. Please revert.

**Comment by waddlesplash** [comment]
> I also think it was too fast. Please revert.

What does "too fast" mean here? QupZilla has not seen *any* commits for 2 years; it's not like it was removed the moment it was deprecated!

> Otter under Linux doesn't work with the user guide site either.

Did you file a bug with Otter? I think the the issue is what PulkoMandy noted, so it would be good to convey that to the Otter developers. But in the meantime, that means I can patch the Userguide Translator.

**Comment by waddlesplash** [comment]
I've deployed a new version of the userguide translator that uses relative URLs for XHRs. See if that helps.

**Comment by Briseur** [comment]
Honestly, absence of commits simply doesn't work. Or, you should also removed all things still using layouts deprecated two times already...
It's not that I don't understand the decision but it gives the bad impression that you decide on your own what's best for us. Some people will never accept that. For some, that the reason why they chose an alternative open source OS.

Anyway, I think that there shall be something to announce software that will be removed.
Maybe not doing that for every piece of software but if the software provides an important functionality (mailer, browser, messenger, chat...) or according popularity (for example above 3 stars with at least 10 votes).

I can imagine,
 * a pinned thread on the forum with a short explanation of the upcoming removals (deprecation, vulnerabilities, no people to maintain, etc...);
 * a RSS feed, well advertised and known of all users, that would group deprecation notices from all depots;
 * a pop-up in HaikuDepot when you try to install such software. I.e. : "Due to lack of support, this software will be soon removed from our Repositories. Please, envisage an alternative." "Do you still want to proceed to installation?"

Then after six months, you can reevaluate and take decision of removal but you gave time
* for everyone (not only devs) to see the warning, (Ask yourself, Who had knowledge of this removal, let's say, a week ago? Who even knows today except people here?)
* for the development of a thing to solve eventual lack of functionality, (like in this case...)
* for people to react and save the software.
Then nobody will complain if there is a removal and, if they do they do, you can argue that they were warned.

**Comment by waddlesplash** [comment]
> Honestly, absence of commits simply doesn't work. 

The software has been deprecated, archived, and the original developers moved on to Falkon, which is QtWebEngine-based so we have no port of it. So, why does that not work?

This ticket, for instance, will never be solved because it's a QupZilla bug, not a bug in our port. Otter, I think, handles this correctly. So why not switch?

> Or, you should also removed all things still using layouts deprecated two times already...

I'm not sure what you mean by this...?

>It's not that I don't understand the decision but it gives the bad impression that you decide on your own what's best for us.

We didn't decide that. Haiku is not a walled garden, you can install stuff outside of HaikuPorts, and plenty of people do. But we make no claims about its stability, and if things are broken we won't fix them. We don't have the manpower to support Qt software that the authors deprecated.

We have removed quite a lot of software in the past that had replacements; I'm not sure why this time is any different?

It's not as if running a `pkgman update` after the software was removed will uninstall it for you; it simply disappears from the Depot for installation. So you are still free to continue using it, and to take as much time as you need to migrate off of it; but the fact remains that it is now unsupported.

This isn't a case where the software is still supported and we are just choosing to remove it; it has been out of development for **2 years**, and has a viable alternative (Otter) that even uses the same backend, and moreover has continued tracking the backend. The one site known to be incompatible I've already patched so it should now work on Otter and Web+ where it did not before.

**Comment by humdingerb** [comment]
> The one site known to be incompatible I've already patched so it should now work on Otter and Web+ where it did not before.

Have you checked that? It still doesn't work in either Otter nor Web+ for me.

**Comment by waddlesplash** [comment]
Hmm, I see it's indeed the same error message; that's very strange. I guess it's possible this is a bug in the Userguide Translator somehow, I'll see what happens on Chromium.

**Comment by waddlesplash** [comment]
Ah, I see that the Userguide Translator is actually using Synchronous XHRs. That may be the problem here; I think WebKit required special support for those and Otter/WebPositive may not bother to implement it as they are deprecated. I'll work on this more later.

**Comment by pulkomandy** [comment]
What would be special about that? It's just an HTTP request from the network backend point of view and it's been used everywhere for a decade. The message is strange, it complains that the request is "cross origin" (meaning it tries to reach another domain than the one the page was loaded from), when it apparently isn't.

Cross-origin prevention is a "new" things (compared to the userguide translator, at least) but I don't understand why it would see a problem here.
