### ISSUE TITLE
TuxPaint doesn't open saved images

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#3045]
On start TuxPaint opens the last saved image, but when trying to open other saved images it doesn't seem to find it

**Comment by threedeyes** [comment]
![dirent](https://user-images.githubusercontent.com/2559260/84831878-7cceaf80-b06f-11ea-8a94-8ecb92903161.png)

This is due to differences in dirent structures. TuxPaint sorts an array of structures in memory for files to open.
As a result, the d_name field is lost during sorting.
Left structure in linux, right in haiku.

I try to fix it for haiku.

**Comment by threedeyes** [comment]
ta-da!
It's works
![screenshot126](https://user-images.githubusercontent.com/2559260/84838548-0d13f100-b07e-11ea-969c-83f19d6fd280.png)

**Comment by Begasus** [comment]
Thanks @threedeyes ! I'll try to see if we could get this change up streamed for future release :)

**Comment by billkendrick** [comment]
Applied. Thanks! :) https://sourceforge.net/p/tuxpaint/tuxpaint/ci/e87f36d9a70a748e717cf28c6a0c2df24924e39f/

**Comment by Begasus** [comment]
Thanks!

Op di 23 jun. 2020 om 08:05 schreef Bill Kendrick <notifications@github.com
