### ISSUE TITLE
mesa_swpipe 17.1.10 visual rendering issues 

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3511]
See: https://discuss.haiku-os.org/t/upgrade-mesa-how-feasible/7936

**Comment by kallisti5** [comment]
For this one, Haiku needs to work with upstream Mesa to develop strategies to be less sensitive to internal API breakages.  As an example, our Mesa softpipe winsys code uses a "random private void* in a struct" to pass our rendered data to a BBitmap within our OpenGL BView.

That void* went away because it was a hack that was no longer needed.    The "real" solution is adding a DRM/DRI compatibility layer within Haiku, or creating our own API for Mesa to interact with our graphics drivers.

**Comment by kallisti5** [comment]
As for the bugs, we just need more folks stepping up and working on Mesa.  I'm no hardcore OpenGL developer, i'm just a guy trying to keep Quake3 running under Haiku :-)

**Comment by kenmays** [comment]
No worries.
![haiku-gearbox](https://user-images.githubusercontent.com/5168719/65723890-28f4e400-e064-11e9-967e-c351939938cf.png)

I may propose something...

**Comment by kenmays** [comment]
Fully tested Mesa 17.1.10, 18.3.6, and 19.2.0. There is a small issue with lp_blend testing. I'll work with the Mesa-devs again after the Mesa 19.1.8/19.2.1 release w/ the latest Haiku patches integrated.  Ticket is resolved as the main concern was in compiling recent versions of Mesa 18.x/19.x on Haiku.
