### ISSUE TITLE
aplayer build fails on x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3697]
Ref: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2619/builds/31789.log

In file included from /sources/APlayer-6a9ce3d3950d929d3a071431ca08c38cc84b1587/APlayer/Players/GameMusic/GMEPlayer.cpp:22:
/sources/APlayer-6a9ce3d3950d929d3a071431ca08c38cc84b1587/APlayer/Players/GameMusic/GMEPlayer.h:27: **gme/gme.h: No such file or directory**

Check **game_music_emu_devel-0.6.1-1-x86_gcc2.hpkg** for missing file: <**gme/gme.h**>

**Comment by kenmays** [comment]
Check: **game_music_emu_devel-0.6.1-1-x86_gcc2.hpkg**
See: APlayer/Players/GameMusic/GMEPlayer.h
// Player headers
#include <gme/gme.h>

**Comment by Begasus** [comment]
Builds ok here, if I check the log it's updating the dependencies for gme and aplayer, maybe gme wasn't updated in that build before aplayer got build?

**Comment by kenmays** [comment]
Thanks for testing. New package: **game_music_emu-0.6.1-2-x86** as of Feb 2019, so no recent build of aplayer was done on build system.  Since no issues with current x86 build testing, closing ticket.

**Comment by mmlr** [comment]
As can be seen from the buildrun entry, aplayer was built against the preexisting gme packages:

```
game_music_emu-0.6.1-1-x86_gcc2.hpkg
game_music_emu_devel-0.6.1-1-x86_gcc2.hpkg
```

See: https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2619&viewMode=expanded

It does however actually depend on gme 0.6.2 and not just any version of gme. Since that dependency is not encoded in the aplayer recipe (it lacks version constraints for `lib:libgme` and `devel:libgme`), the build did not properly depend on the 0.6.2 version (which was arbitrarily built during the same buildrun). So the fix would be to add a `>= 0.6.2` version constraint on the `libgme` dependency in the recipe, not to depend on an arbitrary order of execution of builds.

**Comment by Begasus** [comment]
aplayer only builds on x86_gcc2 libgme 0.6.2 can't be build for x86_gcc2, so it's using 0.6.1, but the revision number is wrong there, in the last buildlog mentioned by @mmlr you can see successful build for game_music_emu-0.6.1-2
Looking at the log for aplayer (shown by @kenmays ) I see it's using /boot/home/haikuports/packages/game_music_emu-0.6.1-1-x86_gcc2.hpkg
Checking aplayer localy I see it's using /boot/system/packages/game_music_emu-0.6.1-2-x86_gcc2.hpkg (and builds ok here)?

**Comment by kenmays** [comment]
@mmlr - We just need to rerun the aplayer recipe on the builders. Last run for aplayer was 2019-02-09 so it was before the new gme revision - and no previous gme packages exist for constraint purposes.
@waddlesplash - Successful build tested by @Begasus
