### ISSUE TITLE
NumPy will try to use AVX/AVX2

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3718]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/2903/builds/13117.log

Excerpt:
```#define HAVE_LINK_AVX 1
#define HAVE_LINK_AVX2 1```

Needs to be changed to not do it.

**Comment by alaviss** [comment]
I've traced the flag to this [file](https://github.com/numpy/numpy/blob/58da56876328e51473ebd4c5ce819262621d5278/numpy/core/include/numpy/npy_common.h#L47).

This is a non-issue. The flag only activates the use of GCC's [Function Multiversioning][0], which allow specialized versions of a function to be run on targeted CPUs, which, in this case are AVX2-supported CPUs. Since this dispatching mechanism works at runtime, no changes should be needed.

[0]: https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Function-Multiversioning.html
