### ISSUE TITLE
Keeping x86 as primary architecture?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4334]
We used to have a separate x86 image for Haiku, that has been long gone, still we use it in the recipes for primary architectures, is it still needed?

**Comment by return** [comment]
@Begasus While it may make sense to remove it now due to the separate x86 arch being merged as a hybrid, however r1beta2 has been pushed back a bit and changing all 'x86' architecture references in recipes might be disruptive (We have to make sure it doesn't break some recipes depending on them first.)

I think 'new recipes' should not have the 'x86' primary arch and after r1beta2 releases, we eventually should remove it as a primary arch.

**Comment by Begasus** [comment]
Agreed on that @return, although I doubt there are still any x86 primary architecture installs still running.

**Comment by Begasus** [comment]
I think this can be closed, the newer recipes don't use primary x86 any more, if older ones get updated they should be removed then.
