### ISSUE TITLE
Qt apps are broken

### ISSUE THREAD

**Issue by ghost** [haikuports/haikuports#5233]
hrev54487 x86_64

Qt apps are broken (Evry Qt app). There is nothing in syslog, neither in Terminal. Apps sprawns only two theards - one with name of application and Bapplication_theard. I tried reinstalling Qt, also deleted evrything with Qt in name in /boot/home/config/settings.

Nothing.

**Comment by threedeyes** [comment]
I can't reproduce this bug.
Haiku and ports updated and all works fine. Strange.
![screenshot82](https://user-images.githubusercontent.com/2559260/89471584-e3e02900-d7c1-11ea-8b61-3d3a4c29f96e.png)

**Comment by premislaus** [comment]
[Archiwum.zip](https://github.com/haikuports/haikuports/files/5031651/Archiwum.zip)
Syslog.

![screenshot1](https://user-images.githubusercontent.com/1739801/89472620-1ddd0b00-d781-11ea-9cff-a6f2d2544f48.png)

~> checkfs /Haiku
        40655 nodes checked,
        0 blocks not allocated,
        0 blocks already set,
        0 blocks could be freed

        files           31096
        directories     8915
        attributes      333
        attr. dirs      262
        indices         49

        direct block runs               43613 (6.91 GiB)
        indirect block runs             350 (in 64 array blocks, 4.27 GiB)
        double indirect block runs      0 (in 0 array blocks, 0 bajtów)

**Comment by premislaus** [comment]
> I can't reproduce this bug.

I can reproduce and I know what breaks them... custom fonts in Appearance. With defaults Qt apps works but I don't want defaults. See - https://premislaus.github.io/05/08/2020/Typografia-fontow-w-Haiku-i-kroje-pisma-w-internecie/

**Comment by threedeyes** [comment]
Try to rebuild fontconfig cache after custom font installations.
**fc-cache -f** or **fc-cache -r**

**Comment by CodeforEvolution** [comment]
Hello @threedeyes!

I was recently looking at your Qt 5 QPA for Haiku over at your repo, and I noticed a while back, you switched from your own custom "QHaikuPlatformFontDatabase" to the "QGenericUnixFontDatabase" which utilizes fontconfig to scan for fonts back in this commit: https://github.com/threedeyes/qthaikuplugins/commit/84735fd77b9958d842a9da125a69fd0c7e1154f2

I was just curious what the reason was for doing this, as there wasn't an associated commit message and I couldn't find any other information. If this was just due to updates in how Qt handles font enumeration, I would be happy to look into re-implementing a "QPlatformFontDatabase" designed for Haiku, as I feel that the manual fontconfig mechanism just isn't very intuitive for the average user wanting to install their own fonts.

**Comment by premislaus** [comment]
> fc-cache -f

Thanks! Works!

**Comment by Begasus** [comment]
For specific app crashes please open a seperate issue, tested and ran a "lot" of Qt apps, so far things work out fine.
