### ISSUE TITLE
LibreOffice cannot directly open files

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#5252]
When double-clicked on a LO file, it does not try to open the file directly. Instead, it launches the application, and then expects us to open the file through the application (through start centre or "Open".

**Comment by waddlesplash** [comment]
LibreOffice should be patched to handle the Qt open file event.

**Comment by threedeyes** [comment]
I do not understand what the problem is? Everything has been implemented and works long ago.
I just checked it on a clean system. Everything works perfectly.

Try launching LibreOffice once with the appropriate launcher to register file types:
![photo_2021-09-03_08-07-52](https://user-images.githubusercontent.com/2559260/131922911-95dd41f0-c9ee-43b1-a3d4-8a7629bab9ce.jpg)


![photo_2021-09-03_07-54-25](https://user-images.githubusercontent.com/2559260/131921368-d2c71877-3eeb-4d71-b30c-7c7db93c62ce.jpg)
![photo_2021-09-03_07-54-31](https://user-images.githubusercontent.com/2559260/131921375-522c8f87-87d6-4da2-91ca-0c194e2053e4.jpg)
![photo_2021-09-03_07-54-35](https://user-images.githubusercontent.com/2559260/131921376-79366a6e-1a67-4cea-a6cc-68b6205f4cdb.jpg)
![photo_2021-09-03_07-54-40](https://user-images.githubusercontent.com/2559260/131921379-142bcae3-c8ee-42b6-be1c-3dc7efa8573b.jpg)

**Comment by bitigchi** [comment]
I followed the same steps as well. First opened through the launcher, saved a file, and when double clicked on that same file it did not open. Right click menu and the open with application list window did not show any LibreOffice.

Are you trying with an English system? Can you try in a fresh system with a different locale and check again?
