### ISSUE TITLE
libreoffice_x86-7.0.1.2-2-x86_gcc2.hpkg cannot open a document.

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#5269]
Open libreoffice and attempt to open a recently saved document.

Libreoffice pegs the cpu 100% and becomes non responsive. The document never opens.

One must kill libreoffice to get the system back.

This makes the program completely useless. I reverted back to libreoffice_x86-6.4.3.1-8-x86_gcc2.hpkg to get the office suite working again.

**Comment by bbjimmy** [comment]
Ok, after removing the settings folder, libreoffice_x86-7.0.1.2-2-x86_gcc2.hpkg crashes on opening a document and does not remember the name of the file when attempting to recover the file. ( hrev54540)

**Comment by diversys** [comment]
Can you attach a debug report? You need to rename it to .txt in order to attach it on github tho.

**Comment by bbjimmy** [comment]
it does not launch the debugger, the program attempts to clean-up so there is no debug report available.

**Comment by CodeforEvolution** [comment]
@bbjimmy, could you check your “/var/log/syslog” for any information? In the past, I have found some crash info there after a program of mine crashed.

**Comment by bbjimmy** [comment]
LibreOffice crash:

http://fatelk.com/jim/LiobreOffoce_crash.png

**Comment by bbjimmy** [comment]
KERN: runtime_loader: Cannot open file /boot/system/apps/LibreOffice/program/libvclplug_gtk3lo.so: No such file or directory
KERN: runtime_loader: Cannot open file /boot/system/apps/LibreOffice/program/libvclplug_genlo.so: No such file or directory
KERN: runtime_loader: Cannot open file /boot/system/apps/LibreOffice/program/libvclplug_gtk3lo.so: No such file or directory
KERN: acquire_advisory_lock(vnode = 0xdaddfed8, flock = 0x82572efc, wait = no)
KERN: Last message repeated 5 times.

**Comment by bbjimmy** [comment]
yup, this lib is not present.

**Comment by CodeforEvolution** [comment]
Strange...I believe I’ve seen that in my own syslog before, though for me, LibreOffice continues to function just fine on my Beta 2 x86_gcc2 virtual machine...

**Comment by diversys** [comment]
> KERN: runtime_loader: Cannot open file /boot/system/apps/LibreOffice/program/libvclplug_gtk3lo.so: No such file or directory
> KERN: runtime_loader: Cannot open file /boot/system/apps/LibreOffice/program/libvclplug_genlo.so: No such file or directory
> KERN: runtime_loader: Cannot open file /boot/system/apps/LibreOffice/program/libvclplug_gtk3lo.so: No such file or directory
> KERN: acquire_advisory_lock(vnode = 0xdaddfed8, flock = 0x82572efc, wait = no)
> KERN: Last message repeated 5 times.

Yes, this is normal. The problem is somewhere else.

**Comment by CodeforEvolution** [comment]
Huh...seems like Haiku people are not the only ones experiencing this: https://ask.libreoffice.org/en/question/259159/libreoffice-7-keeps-crashing/

**Comment by CodeforEvolution** [comment]
@bbjimmy, could you try starting LibreOffice from the command line with the "--safe-mode" option? If that works, you'll then want to try resetting all your user preferences once in LibreOffice...from there, try to normally re-open LibreOffice from the Deskbar.

This is just a solution I saw online...but it's not great...

**Comment by bbjimmy** [comment]
it crashes with  --safe-mode loading a document. safe-mode does not seem to be safe.

**Comment by threedeyes** [comment]
This bug reproduced on Haiku x86_gcc2 only.
On x64 works fine.
I think it's nss3 bug

**Comment by bbjimmy** [comment]
maybe we should revert the gcc2 version until we can update nss3 ( we are several versions behind.)

**Comment by threedeyes** [comment]
we have latest nss 3.56 version

**Comment by bbjimmy** [comment]
maybe mark this version for x86_64 only and re-enable the old version for x86_gcc2

**Comment by unspacyar** [comment]
Hi.  Not sure if it helps, but I notice that, if I tried to open a .TXT file (in Writer), or a .CSV file (in Calc), LibreOffice doesn't crash.  I also  tried saving a spreadsheet in .XLS format (Excel 97-2003), and LibreOffce managed to open it without crash.   (All of this tests, was done in Haiku 32 bit version).

Apparently, the problem is when dealing with her own native file format (ironic, isn't?).  

When opening  .ODS and .ODT files, I get the following output errors in the Terminal:

Open a Writer file:
===============
warn:sfx.dialog:4361:1:sfx2/source/dialog/filtergrouping.cxx:357: already have an element for WordPerfect
warn:sfx.dialog:4361:1:sfx2/source/dialog/filtergrouping.cxx:357: already have an element for writerweb8_writer_template
warn:sfx.dialog:4361:1:sfx2/source/dialog/filtergrouping.cxx:357: already have an element for writerglobal8
warn:vcl.qt5:4361:1:vcl/qt5/Qt5FilePicker.cxx:515: get value on unknown control 100
LibreOffice: ../haiku-git/src/system/libroot/posix/malloc_hoard2/superblock.h:272:int BPrivate::superblock::isValid(): _numBlocks > 0
Abort

Open a Calc file:
==============
warn:sfx.dialog:5278:1:sfx2/source/dialog/filtergrouping.cxx:357: already have an element for WordPerfect
warn:sfx.dialog:5278:1:sfx2/source/dialog/filtergrouping.cxx:357: already have an element for writerweb8_writer_template
warn:sfx.dialog:5278:1:sfx2/source/dialog/filtergrouping.cxx:357: already have an element for writerglobal8
warn:vcl.qt5:5278:1:vcl/qt5/Qt5FilePicker.cxx:515: get value on unknown control 100
warn:sal.osl.pipe:5278:1:sal/osl/unx/pipe.cxx:353: shutdown() failed: ENOTCONN
warn:sal.osl.pipe:5278:3:sal/osl/unx/pipe.cxx:389: accept() failed: -2147479552 (Bad semaphore ID)
/boot/system/apps/LibreOffice/program>

**Comment by waddlesplash** [comment]
Is this still a problem?

**Comment by diversys** [comment]
On 32 bit Haiku we reverted to LibreOffice 6. I tried to build LO 7.2 in a VM with 2GM and ran out of RAM.
