### ISSUE TITLE
ruby: x86 configure build issues on x86

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5366]
ruby 2.7.0->2.7.2 may trigger Haiku debugger during build configuration. Debugger issue seen on hrev54679 x86.

**Comment by extrowerk** [comment]
There is no 2.8 release yet, you meant 2.7.x

**Comment by extrowerk** [comment]
Also you should supply more info, a debugger log for example.

**Comment by kenmays** [comment]
Retested configure for ruby 2.7.0p0 and 2.7.2p137 on hrev54687 x86. No issues.

**Comment by extrowerk** [comment]
This is strange, i have opened a bug some months ago at the ruby bugtracker about the baseruby problem and nobody had any idea.
Now if i try to build ruby with HaikuPorter in 99% it fails because baseruby missing, while in 1% it works with the same recipe.
It seems patching configure.ac and running autoconf is the reason.
