### ISSUE TITLE
pkg-config pass wrong include folder for OpenCV4

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#5596]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1017/builds/1674.log

It seems the include folder passed by pkg-config is wrong. According to the g++ invocation pkg-config returned the following path:
```-I/packages/opencv_x86-4.5.1-2/.self/develop/headers/opencv4/x86```
This looks wrong, i think it should be :
```-I/packages/opencv_x86-4.5.1-2/.self/develop/headers/x86/opencv4```

OpenCV's pkg-config file should be fixed, i assume.

**Comment by extrowerk** [comment]
@Begasus: could you please look into it?

**Comment by extrowerk** [comment]
In the opencv-4.5.1 recipe i had to add this, because https://github.com/haikuports/haikuporter/issues/189 :
```
	# fixPkgconfig
	sed -i 's,\/headers,\/headers/opencv4,g' \
		$prefix/$relativeDevelopLibDir/pkgconfig/opencv4.pc
```

Wrong assumption from my side. a $maybearchdir could be added, or something like that.

**Comment by Begasus** [comment]
Path looks wrong indeed, also in the report it says it's looking for opencv2? 
```
include/IPLImage.h:34:10: fatal error: opencv2/core/core.hpp: No such file or directory
```

**Comment by extrowerk** [comment]
OpenCV puts its headers into 
develop/headers/x86/opencv4/opencv2
Thats ok, and it have to be so, it does the same on other platforms too, for compatibility reasons.

**Comment by Begasus** [comment]
Ah, didn't check so far :) Will give it a run here

**Comment by extrowerk** [comment]
> Ah, didn't check so far :) Will give it a run here

Be warned, it is huge.

**Comment by Begasus** [comment]
I know :) ps, could this work? https://github.com/haikuports/haikuports/blob/f85fb2d8ddbc31ce149a3395a48ff1cca61c05c9/dev-lang/python/python36-3.6.9.recipe#L127

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/5597 (ImagePlay builds fine on x86_gcc2 now - revbump needed for it)
The recipe here on 32-bit fails for not having the data for the python lib, on buildbot it is ok now, sadly now 64-bit sees the same problem I'm facing localy:
32-bit log:
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1018/builds/1675.log
64-bit log:
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5231/builds/18200.log

**Comment by Begasus** [comment]
Build issues have been fixed, I think you can close this one @extrowerk :)

**Comment by extrowerk** [comment]
Thx
