### ISSUE TITLE
haiku -> freetype -> harfbuzz depends on glib

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#5816]
It cause depending core Haiku package on GNOME component glib, that is bad. `libglib-2.0.so.0` is not loaded to native Haiku applications so it should be not needed.

**Comment by korli** [comment]
libglib2 is a reasonable dependency. I agree the packaging could be slimmer.

**Comment by X547** [comment]
It is not actually used (it is not present in team loaded images) so dependency should be optional.

**Comment by X547** [comment]
https://github.com/centricular/harfbuzz/issues/2

**Comment by korli** [comment]
We build as supported upstream.

**Comment by pulkomandy** [comment]
My understanding is that harfbuzz relies on lower level libraries for unicode support, but can use either glib or icu https://github.com/harfbuzz/harfbuzz/blob/master/meson_options.txt, https://github.com/harfbuzz/harfbuzz/blob/19e096aa97b1b3af21313df5250a937ddfece7fb/meson.build#L356). In Haiku case it would make more sense to use the ICU version since ICU is already a dependency of Haiku.

**Comment by X547** [comment]
> In Haiku case it would make more sense to use the ICU version since ICU is already a dependency of Haiku.

+1

**Comment by pulkomandy** [comment]
Dependency removed in 666eddf91356487822ec2e966f95f92b8e06d28e.
