### ISSUE TITLE
digiKam & showFoto crashes (Beta 2)

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#5897]
Before wiping my Haiku (B2) system and reinstalling a "clean" Haiku system, digiKam & ShowPhoto would either crash/freeze the system forcing a hard reboot or it would show an error window. Now after the "clean" install, I have only experiencd the error windows (refer to digiKam_error_msg_2021-05-11_23-14.png as an example).

I attached the "Save report"s: digiKam-2211-debug-11-05-2021-23-15-10.report & showFoto-1082-debug-11-05-2021-22-36-38.report. Not much in them--it seems debugger crashes as well due to what digiKam or showFoto has done to the system (I suspect).

The only applications installed in the system at this time are the stock software from the base install; however, I had to install OpenSound [Open Sound System (OSS)] to get system sounds working by blacklisting and FlameShot for screen captures.

[Cannot seem to attach files using Web+]

**Comment by Brunobasta** [comment]
Use the add-on "UploadIt" found on HaikuDepot.
It will convert your files to a URL that you can insert with Alt-V in the text then.
You can right-click on your .png or your .report click add-on Upload it and alt+v to insert the generated Url in your text here. Example: http://0x0.st/-e64.report

**Comment by ArDrakho** [comment]
Well, here you go:

http://0x0.st/-_cL.png

http://0x0.st/-_c9.report

http://0x0.st/-_cp.report

**Comment by ArDrakho** [comment]
Let me know if you need any other information.

**Comment by ArDrakho** [comment]
I also so happened to have the Terminal open running 'top' when I started digiKam & showFoto at different times. Each time, they crashed with the windows (as in the attached screenshot) and looked at the digiKam max out in top display. Once I cleared the window, digiKam process cleared off the table and then I noticved the 'low resource man' max out thereafter and then it clears of the table. So digiKam & showFoto, is maxing out one of my resources...not sure which yet. I suspect CPU since I see that in the ProcessController.

**Comment by ArDrakho** [comment]
I attached two AVI files capturing what I see when they digiKam & showFoto crash each time.

http://0x0.st/-_pu.avi

http://0x0.st/-_pQ.avi

I hope this helps you all...

**Comment by ArDrakho** [comment]
Well, after updating the respositories as instructed, I forgot to turn off the nightlies...so I ended up upgrading to haiku-r1~beta3_hrev55206-1-x86_64 temporarily. So I decided to check if digiKam works even with this upgrade and unfortunately the problem still exists.

http://0x0.st/-fh3.report

**Comment by wattoc** [comment]
I took a look at this, same issue here.

Running through Debugger it seems to fault around a call to blas_memory_alloc which I believe OpenCV uses, but maybe some other libs are using it too.  Not sure why it'd be called that early if it's OpenCV, since I think that's used for face detection - who knows though.

Trying to build locally for some further investigation and it's taking absolutely ages, so not sure this is an easy one to fix.

**Comment by ArDrakho** [comment]
Let me know if you need anything else.

**Comment by threedeyes** [comment]
This is not a digikam issue, this is a bug in the openblas package. If you roll back openblas to version 0.3.9 - digikam will work fine.
This problem in the new version of openblas does not appear on all CPUs, for example, everything works well for me on AMD Rizen 7. I think the problem is with some kind of optimizations.

**Comment by wattoc** [comment]
Yes I figured it was probably openblas after seeing some more issues around it - looks like there were problems running the tests in the build system at one point.  

Oddly it works fine on my Ryzen 9 laptop but not my Ryzen 5 desktop.  Both of these are Zen 2 based, one is Renoir the other Matisse - not sure if they gained any features that'd be relevant but I guess it's a starting point.

I can try messing about with the build for the current openblas recipe and see if I can get it running, but our issues may have been fixed in a later version too.

**Comment by wattoc** [comment]
I got OpenBlas 3.15 to build fully on my Ryzen 5 and digiKam and showFoto both load up now.  Needs some further testing here and need to confirm exactly which build tweak I used that got it going again.

**Comment by ArDrakho** [comment]
I have openblas-0.3.13-1--so how do I downgrade to openblas-0.3.9?

HaikuDepot does not have that functionality...wish it did plus with options to select or deselect what updates to be apllied. I think that will be included soon...

**Comment by wattoc** [comment]
> I have openblas-0.3.13-1--so how do I downgrade to openblas-0.3.9?

I would instead suggest you try to build openblas 0.3.15, this is already in HaikuPorts, it's just not passing all the tests on the build server.  You'll need to get haikuporter set up, there are instructions in the wiki: https://github.com/haikuports/haikuports/wiki

I can maybe attach the package here otherwise.

If you want 0.3.9 you could probably find the recipe for it on the repo, then copy it to the sci-libs/openblas folder of your local copy of HaikuPorts, and build it after disabling or removing the 0.3.15.

**Comment by wattoc** [comment]
@ArDrakho got another option for you to try also:

Open up Terminal in Haiku, and type in:

`export OMP_NUM_THREADS=4
/system/apps/digiKam/digiKam
`

Let me know if it launches.

**Comment by humdingerb** [comment]
> HaikuDepot does not have that functionality...wish it did plus with options to select or deselect what updates to be apllied. I think that will be included soon...

Until then, you can go to HDS to fnd and download "_All versions_" of a package:
https://depot.haiku-os.org/#!/pkg/openblas?bcguid=bc286-RSTO#%2F%3Fbcguid=bc1-NSYT&arch=x86_gcc2&viewcrttyp=FEATURED&repos=haikuports

**Comment by Begasus** [comment]
@humdingerb those produce: 404 Not Found

**Comment by ArDrakho** [comment]
@wattoc 

> @ArDrakho got another option for you to try also:
> 
> Open up Terminal in Haiku, and type in:
> 
> `export OMP_NUM_THREADS=4`
> `/system/apps/digiKam/digiKam`
> 
> Let me know if it launches.

Woohoo!!!  See attached files: http://0x0.st/-Wii.png & http://0x0.st/-Wio.png

digiKam & showFoto start manually in the terminal where I performed a quick set-up and now face a question, which I do not know how to answer--so I chose 'Cancel' unless there is a readme file that explains what to do for this query.

I hope this helps you solving this issue!

Thanks!!!

**Comment by ArDrakho** [comment]
> > HaikuDepot does not have that functionality...wish it did plus with options to select or deselect what updates to be apllied. I think that will be included soon...
> 
> Until then, you can go to HDS to fnd and download "_All versions_" of a package:
> https://depot.haiku-os.org/#!/pkg/openblas?bcguid=bc286-RSTO#%2F%3Fbcguid=bc1-NSYT&arch=x86_gcc2&viewcrttyp=FEATURED&repos=haikuports

Thanks for the info...never used this Web site before. But when I select v0.3.9, it takes me to its page and when Iselect "Download package 'hpkg' file"--I get a 404 message as Begasus states above.

**Comment by humdingerb** [comment]
Sorry about that. It used to work... I'll open a ticket at HDS, if I don't forget...

**Comment by wattoc** [comment]
> 
> digiKam & showFoto start manually in the terminal where I performed a quick set-up and now face a question, which I do not know how to answer--so I chose 'Cancel' unless there is a readme file that explains what to do for this query.
> 
> I hope this helps you solving this issue!
> 
> Thanks!!!

So as in the image text, digiKam/showFoto need to download some files to enable face detection and red-eye removal.  If you don't download these files, the features won't work and they'll be disabled.  I believe these are binaries for the AI processing involved in these tasks.  I'm not an expert on these programs, I'm just trying to get bugs fixed - unfortunately I can't really help too much with this.

I have a pull request #6094 which assuming it gets merged in it'd be good if you could test again once available so we can close this ticket.  I'll tag you again when this happens.

**Comment by wattoc** [comment]
@ArDrakho a patched version of OpenBLAS should be in HaikuDepot soon/now.

Can you please test and close this ticket if it opens up OK?

**Comment by ArDrakho** [comment]
It is now working!!  

After today's system update, I noticed the latest update for openBLAS was included. 

I want to thank everyone for their comments and the devs for their work!!

**Comment by ArDrakho** [comment]
Well...the answer to my query above  regarding "digiKam/showFoto need to download some files to enable face detection and red-eye removal"--go for it! It saves the necessary files into "/boot/system/cache/{digikam|showfote}/facesengine". And it works as far as I can tell.

I imported some photos in both applications...played with the files for a bit---so far so good!

I would this issue closed now!!
