### ISSUE TITLE
gcc 8.3.0: no RISC-V configuration

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#6136]
version: gcc-8.3.0_2019_05_24.

GCC package source differs from buildtools and RISC-V configuration is missing in `config.gcc` causing "gcc configuration not supported" error when building.

**Comment by waddlesplash** [comment]
To be honest I don't know why we have two totally separate patchsets for GCC instead of just building the recipe based on buildtools. @korli, do you know?

**Comment by korli** [comment]
Because nobody ever upstreamed any patches?

**Comment by pulkomandy** [comment]
It was not possible to upstream patches due to copyright assignments requirement from gcc. They used to require that all contributors reassign their copyright to the FSF before they accept any patch. It is unknown how far back our patches go and who contributed to them (probably some of it can be traced back to the gcc2 port to BeOS).

This restriction on gcc side has been removed recently, so we could consider upstreaming the changes.

The question is, why does the recipe use the upstream gcc sources, and does not build from our buildtools repository intead? Wouldn't it be simpler to use our buildtools repository instead of maintaining a copy of the same patches in the haikuports recipe, at least in the short term? (in the long term it's of course better to upstream our changes to gcc and stop having a buildtools repo in its current form)

**Comment by korli** [comment]
Building from a tarball is always easier.

**Comment by X547** [comment]
> Because nobody ever upstreamed any patches?

Why not use buildtools version everywhere (haikuports, haikuports.cross)? Why separate version is needed?

**Comment by waddlesplash** [comment]
Well, if nobody knows why the buildtools version is not used, sounds like a good reason to switch to it (or back to it.)

**Comment by waddlesplash** [comment]
(The patches probably need to be carefully compared however...)

**Comment by X547** [comment]
This also should be switched to buildtools: https://github.com/haikuports/haikuports.cross/blob/master/sys-devel/binutils_bootstrap/binutils_bootstrap-2.28.1_2017_08_05.recipe. haikuports.cross GCC already did it.

**Comment by pulkomandy** [comment]
As korli mentionned, there are no tar.gz or tags on the buildtools, and the archive is larger because it includes two versions of gcc and binutils in a single repository. That's the only reason it was not used, as far as I can see. It also potentially allows having different versions of gcc available in the repo even if they can't compile the OS itself yet, but I'm not sure if we want to go down that way. If we don't, we should think about updating our gcc in buildtools, however...

**Comment by jmairboeck** [comment]
cgit allows downloading snapshots, although I see it is disabled in the Haiku instance (https://github.com/haiku/infrastructure/blob/master/containers/cgit/assets/cgitrc.template#L84). That would allow using btrev tags as version number.

**Comment by waddlesplash** [comment]
They usually get regenerated and thus have differing sha256sums so that would not be useful anyway.

**Comment by X547** [comment]
I managed to build functional GCC packages with this recipe and code from buildtools.

**Comment by Begasus** [comment]
Stil valid?

**Comment by X547** [comment]
It is solved for quite a long time. Current HaikuPorts GCC builds on riscv64 platform and produce functional executables.

**Comment by Begasus** [comment]
Thanks for responding back! :)
