### ISSUE TITLE
update the haikuporter recipe

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#6195]
The recipe for haikuporter should be updated to a version that includes support for `ARCHITECTURES="all"`.

Probably a new version of haikuporter should be tagged for that. Should I also open an issue in haikuporter for that?

**Comment by waddlesplash** [comment]
Yes.

Although there were one or two other HaikuPorter changes I wanted to throw in before cutting off a new release, which is why I haven't done that yet.

**Comment by scottmc** [comment]
Fresh install of Haiku R1B3, installed haikuporter from HaikuDepot, tried to build something...  
Error:....    port.recipe refers to unknown architecture all  

Checked haikuporter --version, it shows 1.2.2

So I did a git clone and got 1.2.5, I tried building and still get unknown architecture all  

This is NOT good.  

Please fix it so that new/old users can install and have it just work again.  From my view, the basic tool that is used to build everything from haikuports is currently in a broken state.

**Comment by Begasus** [comment]
Everything is working fine here on R1B3 (32bit), I always use the cloned version that I regularly update after new commits?
64bit is nightly and working fine too, but granted, the one in the depot should be updated.

**Comment by korli** [comment]
- [ ] draft a release
- [ ] bump the haikuporter recipe

**Comment by pulkomandy** [comment]
Yes.
