### ISSUE TITLE
Cutter crashes when launched from the Deskbar menu/Tracker

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#6215]
For now you need to launch Cutter in Terminal

Debug report:

[Cutter-90985-debug-29-09-2021-13-33-49.report.txt](https://github.com/haikuports/haikuports/files/7254025/Cutter-90985-debug-29-09-2021-13-33-49.report.txt)

**Comment by korli** [comment]
As a workaround, one can use a bash script as launcher and add it to the deskbar.

**Comment by Begasus** [comment]
Maybe something for hacktoberfest :)

**Comment by thestr4ng3r** [comment]
Some more info about the crash:
It happens here: https://github.com/rizinorg/cutter/blob/12df7a001dea64f65222434b5b5a7a94c1d92e06/src/widgets/ConsoleWidget.cpp#L427 where `origStderr` is `NULL`.
That is because the `fdopen` calls starting at https://github.com/rizinorg/cutter/blob/12df7a001dea64f65222434b5b5a7a94c1d92e06/src/widgets/ConsoleWidget.cpp#L452 fail with `EINVAL`, probably because something is different with stdin/stdout/stderr when not run from a terminal.

Are there any man pages in haiku for the POSIX/C functions?
From Linux, the causes could be:
```
ERRORS
       EINVAL The mode provided to fopen(), fdopen(), or freopen() was invalid.
       The fopen(), fdopen(), and freopen() functions may also fail and set errno for any of the errors specified for the routine malloc(3).
       The fdopen() function may also fail and set errno for any of the errors specified for the routine fcntl(2).
```
with `fcntl` in the mix, there are quite a lot of sources for this errno.

Is there any way on haiku to get debug symbols and source for libroot so one can debug into the implementation of `fdopen` itself?

**Comment by Begasus** [comment]
@thestr4ng3r thanks for upstream patch! Looking into bumping rizin/cutter to the latest version, will report back later :)

**Comment by Begasus** [comment]
This can be closed, Cutter launches OK from Deskbar/Tracker now, new crash (seperate issue here) for a crash when trying to access the preferences.
