### ISSUE TITLE
Create Haiku-style icon for Kristall

### ISSUE THREAD

**Issue by win8linux** [haikuports/haikuports#6259]
[Kristall's recipe](https://github.com/haikuports/haikuports/pull/5359) has an icon, but it doesn't quite fit in with the rest of Haiku.

Kristall icon for reference:
![image](https://user-images.githubusercontent.com/11584387/136697121-fcca62d2-1977-4f17-8a2a-0abbdb1c826d.png)
[SVG](https://github.com/MasterQ32/kristall/blob/master/src/icons/kristall.svg)

**Comment by pulkomandy** [comment]
The icon for Ruby here may be used as a base: https://haikuarchives.github.io/ZumisIcons/myhaiku/3rd%20party%20apps/index.html but needs recoloring

**Comment by Handmaus** [comment]
Hello, i have made an icon for this program.
Already tried recoloring zuMi's Ruby icon, as Pulkomandy suggested, but it doesn't felt really ok, as it looked too good and a bit out of place, as this program is a browser for protocols that aim to be a return to a simpler internet.
So i decided to go the extra mile and create an icon that adapts to Haiku's style, but that also respects the program's spirit trying to retain the Kristall logo simplicity.
It's also my first successful attempt at creating something with Icon-o-Matic that at least don't make anyone's eyes bleed.
I'm such a brick using this program -_-
Hope you like it :)

![Kristall HaikuStyle B 03 Clear 03](https://user-images.githubusercontent.com/92672828/137625639-0a970cec-569c-447b-a8cb-fe2965150030.png)

BTW: I'm a total beginner in regards to this git thing (signed up in GitHub just today), and naturally there's a lot of doubts that come to my mind.
But there's this thing that strikes me the most after reading the contributing guidelines:
 is it really needed to download the thousands of sources contained in the entire Haikuports repository (isn't that what happens when you "fork" and "clone"?), then do one of this "pull requests", just to contribute an icon to one recipe?
Maybe in the end is not that big of a deal, but it sure feels a bit overwhelming to a non-coder like me.
As i don't want to make you wait another year, for me to learn how to do it the proper way, in the meantime here's the hvif attached to this message:
[Kristall.hvif.zip](https://github.com/haikuports/haikuports/files/7360143/Kristall.hvif.zip)
If something else is needed, please ask.

**Comment by pulkomandy** [comment]
> is it really needed to download the thousands of sources contained in the entire Haikuports repository (isn't that what happens when you "fork" and "clone"?), then do one of this "pull requests", just to contribute an icon to one recipe?

There are ways around it, but if you plan to contribute more things later, it ends up being simpler that way.

I'm sure someone will find the time to integrate your icon in the recipe, still :)
