### ISSUE TITLE
gcc11: duplicated libraries in gcc package

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#6470]
gcc package has the following libraries in `/system/develop/tools/lib/gcc/x86_64-unknown-haiku/11.2.0`
```
libatomic.so.1.2.0
libgcc_s.so.1
libgfortran.so.5.0.0
libgomp.so.1.0.0
liblto_plugin.so
libobjc.so.4.0.0
libquadmath.so.0.0.0
libssp.so.0.0.0
libstdc++.so.6.0.29
```
which seems to be duplicating the same ones in `/system/develop/lib`. Is it supposed to be like that?
Also, does libgfortran needs to be in the main gcc package?

**Comment by extrowerk** [comment]
AFAIR: I was told libgfortran should be in the main package back then as i enabled fortran.

**Comment by waddlesplash** [comment]
They are really copies, not symlinks? (Actually they might be intended to be hardlinks...)

**Comment by diversys** [comment]
Really copies, yes.

**Comment by Begasus** [comment]
Still an issue?

**Comment by nielx** [comment]
I have reviewed the previous implementation in PR #6704 by @extrowerk, and I just wanted to make sure that this is the path we would go down on. 

In extrowerk's implementation, the libraries would only be a part of gcc_syslibs. That means that the gcc package will have links. This means that we might be introducing a new dependency between gcc and gcc_syslibs, though it is hard to tell, since gcc_syslibs is technically a required package for any Haiku installation, so I doubt we have ever run the gcc command without gcc_syslibs being present.

Questions:
1.  Are we okay with introducing a dependency of the gcc package on gcc-syslibs?
2. And if so, should this be an implicit dependency, or should it be made explicit in the requires section of the package?

We could leave it the way it is right now. These libraries are not big by any means,

**Comment by pulkomandy** [comment]
I think an explicit dependency is the way to go here.

The concern with the duplicate libraries is not necessarily the wasted space, but also the fact that the two versions can be out of sync. Should this be allowed? Is it desirable?
