### ISSUE TITLE
[GTK3] Apply GTK3-Classic patches?

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6549]
https://github.com/lah7/gtk3-classic

These (plus a Haiku BControlLook theme, but that will probably come much later if at all) will provide much better integration and make GTK3 applications less "foreign", I think?

**Comment by khallebal** [comment]
I think the BControlLook theme can easily be created by someone who knows his way around the css language, there is already one available, which i tried to modify but it's difficult for me as i don't understand half of the terminology involved.

**Comment by nephele-gh** [comment]
The problem is that a BControlLook is allowed to control the rendering pretty completely. While you can make a css theme to immitate HaikuControlLook it would be quite hard to make one that automatically matches the system controll look with css. 
Maybe there is a different mechanism that is better suited for this? The qt port also uses native drawing methods for it's rendering.

**Comment by khallebal** [comment]
Yeah, you're probably right.

**Comment by waddlesplash** [comment]
GTK3-classic patches are applied by the recipe now. Thanks @threedeyes!
