### ISSUE TITLE
Error trying to install yt_dlp:  nothing provides cmd:python3>=3.7.14 needed by yt_dlp-2022.10.04-1

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#7336]
Hi. Yt-dlp package apparently needs to be rebuild.  I got this message when trying to install it (on Haiku 32 bit):

nothing provides cmd:python3>=3.7.14 needed by yt_dlp-2022.10.04-1

Thank you!

**Comment by korli** [comment]
Obviously there should be more than this one. I looked for the repo_consistency report, but couldn't find a working URL anymore.

**Comment by Begasus** [comment]
> Obviously there should be more than this one. I looked for the repo_consistency report, but couldn't find a working URL anymore.

There hasn't been any reports that (unlike in the past) reported broken builds due to broken dependencies for a while ...

**Comment by korli** [comment]
> There hasn't been any reports that (unlike in the past) reported broken builds due to broken dependencies for a while ...

I thought this is now hidden somehow at https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current/
@kallisti5  any repo_consistency.txt reports URLs available?

**Comment by Begasus** [comment]
The report is up at: https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current/report.txt

But doesn't show any broken dependencies anymore

**Comment by korli** [comment]
Should be repo_consistency.txt : https://github.com/haikuports/haikuporter/blob/master/buildmaster/backend/assets/loop#L32

https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current/repo_consistency.txt but it looks empty

report.txt is the repository creation: https://github.com/haikuports/haikuporter/blob/master/buildmaster/backend/assets/loop#L115

**Comment by mmlr** [comment]
An empty repository consistency report is generally what you want, as it would mean no issues have been found. This is where that report is being triggered:

https://github.com/haikuports/haikuporter/blob/master/buildmaster/backend/assets/loop#L31

Since there is no output at all, it is also possible that the command failed and that isn't seen in the report because stderr is not being captured. The logs of the buildmaster containers should show which case we have here, but I don't have access to those. It would probably make sense to change the line there and add stderr redirection so that it would be more obvious when it fails (as in adding "2>&1").

Some output could be added to the command as well so that it can be seen whether or not it ran to completion. The code would need to go into this function:

https://github.com/haikuports/haikuporter/blob/master/HaikuPorter/Repository.py#L627

A message like "repository consistency check completed" would suffice I guess, maybe even with a date.

**Comment by Begasus** [comment]
@unspacyar could you re-check, version bump has just been build on buildmaster and should be ready for installation.

**Comment by unspacyar** [comment]
Hi.  Sorry for my late answer.  Allow me until next sunday to test it. Thanks!

**Comment by unspacyar** [comment]
I confirm that the issue was fixed. Thank you @Begasus
