### ISSUE TITLE
ALEditor doesn't run on Haiku Beta4 test

### ISSUE THREAD

**Issue by codewrangler1** [haikuports/haikuports#7503]
Unresolved symbol error.

<img width="356" alt="Screen Shot 2022-11-23 at 6 27 01 AM" src="https://user-images.githubusercontent.com/5871310/204820491-7b1d95fc-e1a3-405b-8238-56e40ec9348e.png">

**Comment by waddlesplash** [comment]
should be fixed after https://github.com/haikuports/haikuports/commit/f955a686ec34ae2c4edda1686956b74bda42c349

**Comment by diversys** [comment]
Rebuilding didn't help.

**Comment by pulkomandy** [comment]
This function is provided in Haiku by liblinprog static library. However that library is not provided in haiku_devel. It used to work because the symbols were re-exported by libalm, which the libale.so built as part of ALE links against.

Should libalm continue to export these symbols or should liblinprog be made available in haiku_devel?

liblinprog exists as a separate static library because it is also used by app_server for Stack&Tile support.

**Comment by SamuraiCrow** [comment]
What are the disadvantages of including the existing linker lib in Haiku_devel?  If it's used for stack and tile already, should it be converted into a shared object to improve maintainability?  If I weren't wandering around Haiku sources and docs like a lost soul looking for meaning, I might be able to take this on.  Maybe I can!

**Comment by pulkomandy** [comment]
Here is the patch that should make these symbols visible again in libalm, restoring how it worked before Haiku buildsystem started hiding symbols in static libraries by default: https://review.haiku-os.org/c/haiku/+/6664

**Comment by SamuraiCrow** [comment]
Thanks, Pulkomandy!

**Comment by augiedoggie** [comment]
ALE was added in 8f97be08c615977ede7b1e7e7a100db52c7e3fb5
