### ISSUE TITLE
*.info files

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#7703]
Some package provide these and are installed in $docDir/info (got 133 files installed atm on my 32bit install), are these supposed to stay/keep?
I've seen packages where they are deleted from the package.
If thy should be deleted, any specific reason? Or if they should stay, any specific reason?
Would be nice if this could be cleared out. :)

**Comment by SamuraiCrow** [comment]
On an Amiga-like OS .info files are the icon information and contain a cookie-like configuration property also.  These should be deleted and changed to use the config file and HVIF equivalents.

On POSIX platforms there is a documentation viewer called Info that is a man-page equivalent.  These should be stored in $documentationDir/info instead of $docDir/info I think.  If there is a way to convert them to another format, that might be better.

**Comment by waddlesplash** [comment]
Can you view them with `man`? If so, then that's fine, they can be left in place.

**Comment by Begasus** [comment]
You can just open them with Pe or any text editor, from first looks it seems they are generated by makeinfo (.texi -> .info), some can't be opened (not even with man).

**Comment by Begasus** [comment]
Just noticed opening them can be done with `info aspell` (example). So this can be closed.
