### ISSUE TITLE
libkwix: build failure on x86

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#7894]
meson can't find libzim

https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3795/builds/79762.log

**Comment by Begasus** [comment]
This is caused by the update on meson, the pkgconfig file now gets installed in `Installing /sources/libzim-8.0.1/build/meson-private/libzim.pc to /packages/libzim_x86-8.0.1-2/.self/develop/lib/pkgconfig` instead of `Installing /sources/libzim-8.0.1/build/meson-private/libzim.pc to /packages/libzim_x86-8.0.1-2/.self/develop/lib/x86/pkgconfig`

See: https://github.com/haikuports/haikuports/pull/7792/files#diff-a370e674803db4f544777a48590802a932abca0728b4696464769b4316aaee9eR238

**Comment by Begasus** [comment]
Once buildmaster on 32bit is online again libzim could get a revbump after meson is rebuild, that should fix building libkiwix

**Comment by Begasus** [comment]
Closing as completed in: https://github.com/haikuports/haikuports/pull/7937
