### ISSUE TITLE
How to deal with dates?

### ISSUE THREAD

**Issue by n0toose** [haikuports/haikuports#7952]
Some packages, e.g. https://github.com/haikuports/haikuports/blob/19dd8691d9636c0b598cd20ad25179bb0988d449/games-action/ddnet/ddnet-2023.03.09.recipe, require splitting dates using dots so that their respective `.rdef` files can have versions.

However, we very often use the a format that looks somewhat like `20230312` instead of `2023.03.12`. Should we make that consistent?

**Comment by pulkomandy** [comment]
All fields in rdef files are optional. So if some software has a major version of "20230309", no minor and no revision, that's fine.

There's no need to standardize here, we have to follow what upstream decides to do. And be angry at them when they change versionning schemes and the next version is 1.0 or something, and our package installer doesn't automatically update because 1 is less than 20230309.

**Comment by korli** [comment]
Is there still something to discuss here?

**Comment by pulkomandy** [comment]
I don't think so.
