### ISSUE TITLE
Perl: 5.18.2 has reached EOL 

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#856]
Minimum upgrade to 5.22.2.

**Comment by miqlas** [comment]
Updated patchset to 5.24.0: https://gist.github.com/f066db4421fd958dfc07989992130cc0
Doesn't works yet and i lost all the subjects. If it isn't good enough, then just never mind it.

**Comment by zzzzzzzzz** [comment]
I would propose to upgrade to 5.18.4 first (most recent 5.18).  Fix the policy violation to unplug Pulkomandy's bots. Possible solution is to disable libperl.so.  Do we really need it?  According to INSTALL doc in perl's sources. there is more trouble than gain.  Moreover, patch from 5.18.2 is applicable without changes.  

There are major changes since 5.20.  Some core modules were removed (for example long-time core Module::Build).  The pm system cannot even track such changes as perl module is neither library nor executable.  Haiku's perl has still bugs from 5.10, so bumping version from one not maintained version to another is pointless.

**Comment by korli** [comment]
Perl has been updated.
