### ISSUE TITLE
update radare2

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#8854]
Mail from pancake (@radare)
> - not updated since 5.7.2
> - not in sync with disk/haiku (may act as a backup of the haikuports repo)
> - no patches should be needed now
> - not working on i686 version
> - build script is a bit complicated i think it can be simplified
> - acr/make is fine, but it may be possible to use meson if that helps somehow

**Comment by trufae** [comment]
@Begasus the radare2 GUI is named iaito and it can be also packaged for Haiku. It was forked from Cutter the very same day rizin forked radare2. Iaito was the original name of the GUI before being forked as Cutter.

**Comment by Begasus** [comment]
libr doesn't seem to link to libnetwork (although declared in rules.mk), getting undefined references to network functions

**Comment by Begasus** [comment]
First error was: `../libr/include/r_io.h:49:10: fatal error: sys/ptrace.h: No such file or directory` added `&& !defined(__HAIKU__)` there to "fix" that.

**Comment by Begasus** [comment]
OK, didn't get any further building with meson, using configure however produced the package.

**Comment by Begasus** [comment]
Update in progress, package here seems to be fine, just needs cleaning up and some double checks :)

Still got a crash when accessing the  preferences in iaito though, @trufae any idea if this can be fixed (or is fixed upstream)?

```
[x86] ~/wip/iaito-5.8.6> /boot/home/destdir/usr/local/bin/iaito
qt.qpa.openglcontext: Created 0x19033180 based on requested QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::ColorSpace::DefaultColorSpace, profile  QSurfaceFormat::OpenGLContextProfile::NoProfile)
Loading translations path /boot/home/config/non-packaged/data//radare2/iaito/translations
Loading translations path /boot/system/data/Qt5/translations
Plugins are loaded from "/boot/system/cache/radareorg/iaito/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "/boot/home/config/non-packaged/data/radareorg/iaito/plugins"
Plugins are loaded from "/boot/home/config/data/radareorg/iaito/plugins"
Plugins are loaded from "/boot/system/non-packaged/data/radareorg/iaito/plugins"
Plugins are loaded from "/boot/system/data/radareorg/iaito/plugins"
ERROR: Oops. try arn [PC|SP|BP|SN|A0|A1|A2|A3|A4|R0|R1|ZF|SF|NF|OF]
ERROR: Oops. try arn [PC|SP|BP|SN|A0|A1|A2|A3|A4|R0|R1|ZF|SF|NF|OF]
WARN: run r2 with -e bin.cache=true to fix relocations in disassembly
WARN: Cannot resolve symbol address __main_thread_id
WARN: Cannot resolve symbol address __register_frame_info
WARN: Cannot resolve symbol address __cxa_finalize
WARN: Cannot resolve symbol address __deregister_frame_info
WARN: Cannot resolve symbol address stderr
WARN: Cannot resolve symbol address __gxx_personality_v0
WARN: Cannot resolve symbol address argv_save
INFO: Analyze all flags starting with sym. and entry0 (aa)
INFO: Analyze all functions arguments/locals (afva@@@F)
INFO: Analyze function calls (aac)
INFO: Analyze len bytes of instructions for references (aar)
INFO: Finding and parsing C++ vtables (avrr)
INFO: Type matching analysis for all functions (aaft)
INFO: Propagate noreturn information (aanr)
INFO: Use -AA or aaaa to perform additional experimental analysis
Kill Thread
```

**Comment by trufae** [comment]
I think we can disable the debugger for now. i'll hopefully find some time to fix or implement what's missing before the next release! 

About the iaito->settings crash, i would need a backtrace or a crashlog at least to see what's going on because the startup output doesnt gives me any clue.

Thanks!

**Comment by Begasus** [comment]
OK, thanks for the reply, in the meantime I've updated our capstone recipe in a new PR (5.0-rc2) at: https://github.com/haikuports/haikuports/pull/8861

Does that one need more patching to be on par?

**Comment by trufae** [comment]
No extra patches needed for capstone5 if haikuports ships the rc2 that's great! (i have some good feelings that 5.0 will be eventually released this year i will be finally be able to stop depending on git commits).

About this undeclared tricore. it's defined in here capstone `include/capstone/tricore.h:     TRICORE_INS_XOR,`. maybe you are building capstone5 without tricore support?

**Comment by Begasus** [comment]
[iaito-201888-debug-16-06-2023-19-18-54.report.txt](https://github.com/haikuports/haikuports/files/11778052/iaito-201888-debug-16-06-2023-19-18-54.report.txt)

Added debug report here.

**Comment by Begasus** [comment]
> (i have some good feelings that 5.0 will be eventually released this year

Just released (3 hours ago) :) (the tricolor functions were released after rc2, so they weren't in yet) :)

**Comment by Begasus** [comment]
Updated in https://github.com/haikuports/haikuports/pull/8864

**Comment by trufae** [comment]
You are not running the tests properly. The errors report missing files, the r2 testsuite have a separate repo named "testbins" that is pulled when running "make tests", actually all those tests are executed by r2r (unit tests are just 1 a small portion of them). r2r will pull the testbins too. there are more than 25.000 tests, so that may take a while to run if you want to check this after build.

`XX] Fail at line 14: [0mcrackme0x00 binary could not be opened`

About the crashlog. it seems like an internal crash in Qt raised when creating the preferences items, reading the disassembly i have the feeling that it fails in here https://github.com/radareorg/iaito/blob/master/src/dialogs/preferences/PreferencesDialog.cpp#L71

considering the haiku build have debugger disabled, i'm doing the blind guess to assume its the debugger panel which is 
causing the failure, could you try shrinking/commenting portions of the ` QList<PreferenceCategory> prefs` list and see if commenting those makes the crash go away? as a workaround we can have an ifdef there if that solves the problem..

ill do a local build on linux without debugger and see if i can repro the problem here. my haiku box is too slow for testing this.

**Comment by Begasus** [comment]
> that may take a while to run if you want to check this after build

I'll focus on iaito for a bit (also want to get cudatext working and enabled for python3.9), so plenty to do :)
