### ISSUE TITLE
gfortran: missing symbols in libgfortran.so

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#9241]
Context: trying to update the `scipy` recipe, that uses meson/meson_python, and needs among, other things, a working Fortran compiler.

Builds fails with the error message:

    ERROR: Executables created by fortran compiler gfortran are not runnable.

---

Meson attemps to buid and run the following `sanitycheckf.f90` program:

```fortran
program main; print *, "Fortran compilation is working."; end program
```

compiling it with `gfortran sanitycheckf.f90 -o sanitycheckf.exe`

Running `sanitycheckf.exe` results in runtime_loader errors:

```
runtime_loader: /boot/system/lib/x86/libgfortran.so.5.0.0: Could not resolve symbol 'dl_iterate_phdr'
resolve symbol "dl_iterate_phdr" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libgfortran.so.5.0.0: Troubles relocating: Symbol not found
```

Compiling with `gfortran sanitycheckf.f90 -lbsd -o sanitycheckf.exe`

makes the executable work.

Is `libgfortran.so` somehow not being link to `libbsd` as it seems it should? (otherwise... having to add `-lbsd` everywhere doesn't sounds right to me).

**Comment by bugcrazy** [comment]
Promising result on the forum to resolve the issue: https://discuss.haiku-os.org/t/how-do-i-install-pandas/13965/5

Here: https://github.com/haikuports/haikuports/pull/9424

**Comment by nielx** [comment]
My current hypothesis is that libgfortran depends on libbacktrace in the gcc package, and libbacktrace has conditional support for dl_iterate_phdr. Now the test looks as follows:
```
# Check for dl_iterate_phdr.
AC_CHECK_HEADERS(link.h sys/link.h)
if test "$ac_cv_header_link_h" = "no" -a "$ac_cv_header_sys_link_h" = "no"; then
  have_dl_iterate_phdr=no
else
  if test -n "${with_target_subdir}"; then
    link_h=link.h
    if test "$ac_cv_header_link_h" = "no"; then
       link_h=sys/link.h
    fi
    # When built as a GCC target library, we can't do a link test.
    AC_EGREP_HEADER([dl_iterate_phdr], [$link_h], [have_dl_iterate_phdr=yes],
		    [have_dl_iterate_phdr=no])
  else
    AC_CHECK_FUNC([dl_iterate_phdr], [have_dl_iterate_phdr=yes],
		  [have_dl_iterate_phdr=no])
  fi
fi
```

Usually, it tries to use `AC_CHECK_FUNC` which builds a basic program and links it, as a test. This will fail, because the script does not know about libbsd.so, so it will never succeed. However, the compiler is a multi-stage affair, and I am assuming that at some stage an intermediate compiler (`xgcc`) is used to create the target compiler and its libraries, thus then suddenly the simpler `AC_EGREP_HEADER` test is used, and through that test, it is then assumed dl_iterate_phdr _is_ available.

Potential solutions:
1. Patch the configure script of libbacktrace to make it aware of libbsd.so
2. Disable using dl_iterate_phdr in libbacktrace on Haiku

**Comment by waddlesplash** [comment]
Does GCC's configure have an option to enable usage of `--no-undefined`? (It may not, as parts of the GCC build may depend on building libraries with non-weak intentionally-undefined symbols...)
