### ISSUE TITLE
Qt5

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#999]
After changes in numbering of libpng libs (from 16.X to 1.6.X) the Qt5 packages can't be installed (nothing provides lib:libpng_x86>=16.18.0 error).

**Comment by fbrosson** [comment]
Can you be more explicit about which numbering changes of libpng libs you are referring to and when , approximately, these changes took place?
Because there were no such changes since a long time.
What was changed very recently (i.e. a few days ago) is completely neutral:
* before this recent change we had to manually update the lib versions.
* after this recent change the recipe _computes_ it for us.

**Comment by unspacyar** [comment]
Hi. Sorry for the lack of details.  I guess is related to this issue:
https://dev.haiku-os.org/ticket/13120

I guess the changes were made in the last 30 days.

**Comment by fbrosson** [comment]
OK. Thanks for the pointer.
It looks like the version of lcms_x86 included in our x86_gcc2 nighlies is (or was) a bit old (2.5) compared to what we have in haikuports: 2.8. And maybe there were some version errors in that old recipe.

BTW, the recent changes in our libpng-1.5.x series is OK:
When $portVersion is 1.5.28, libVersion is set to 15.28.0 thanks to this:
```
# define libVersion as xy.z.0 when portVersion is x.y.z.
+libVersion="${portVersion/\./}.0"
```

**Comment by korli** [comment]
This is a built package problem => not handled at Haikuports.
